#!/usr/bin/env bash
# shellcheck shell=bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
source "$SCRIPT_DIR/common_test.sh"

main() {
  local preview_workflow reset_preview_workflow mainnet_workflow
  preview_workflow="$(cat "$REPO_ROOT/.github/workflows/deploy-preview-role-runtime.yml")"
  reset_preview_workflow="$(cat "$REPO_ROOT/.github/workflows/reset-preview-role-runtime.yml")"
  mainnet_workflow="$(cat "$REPO_ROOT/.github/workflows/deploy-mainnet-role-runtime.yml")"

  assert_contains "$preview_workflow" 'app_binaries_release_tag' "preview deploy workflow requires the app-binaries release tag"
  assert_contains "$preview_workflow" 'app_runtime_ami_release_tag' "preview deploy workflow requires the app runtime ami release tag"
  assert_contains "$preview_workflow" 'shared_proof_services_image_release_tag' "preview deploy workflow requires the shared proof image release tag"
  assert_contains "$preview_workflow" 'wireguard_role_ami_release_tag' "preview deploy workflow requires the wireguard ami release tag"
  assert_contains "$preview_workflow" 'operator_stack_ami_release_tag' "preview deploy workflow accepts the operator stack ami tag"
  assert_contains "$preview_workflow" 'resolve-role-runtime-release-inputs.sh' "preview deploy workflow resolves pinned role runtime release manifests"
  assert_contains "$preview_workflow" 'deploy-coordinator.sh' "preview deploy workflow drives the production coordinator"
  assert_contains "$preview_workflow" '--app-binaries-release-tag "${{ inputs.app_binaries_release_tag }}"' "preview deploy workflow refreshes app runtime from the selected app-binaries release"
  assert_contains "$preview_workflow" 'provision-app-edge.sh' "preview deploy workflow provisions the app edge after coordinator rendering"
  assert_contains "$preview_workflow" 'canary-shared-services.sh' "preview deploy workflow runs the shared services canary"
  assert_contains "$preview_workflow" 'canary-app-host.sh' "preview deploy workflow runs the app canary"
  assert_contains "$preview_workflow" 'shared-infra-e2e_linux_amd64' "preview deploy workflow downloads the released shared-infra-e2e binary"
  assert_contains "$preview_workflow" 'queue_driver="$(jq -r' "preview deploy workflow reads the shared queue driver"
  assert_contains "$preview_workflow" 'kafka_path_active="false"' "preview deploy workflow derives active kafka paths"
  assert_contains "$preview_workflow" '--queue-driver "$queue_driver"' "preview deploy workflow validates postgres queue mode"
  assert_contains "$preview_workflow" '--queue-postgres-dsn "$checkpoint_postgres_dsn"' "preview deploy workflow passes postgres queue dsn"
  assert_contains "$preview_workflow" '--required-kafka-topics "$required_topics"' "preview deploy workflow still validates kafka queue mode"
  assert_contains "$preview_workflow" 'deposits.event.v2' "preview deploy workflow validates deposit event kafka topic"
  assert_contains "$preview_workflow" 'withdrawals.requested.v2' "preview deploy workflow validates withdrawal request kafka topic"
  assert_contains "$preview_workflow" 'shared-infra-e2e.kafka-shadow.json' "preview deploy workflow records kafka shadow validation separately"
  assert_contains "$preview_workflow" 'shared-infra-e2e.postgres-shadow.json' "preview deploy workflow records postgres shadow validation separately"
  assert_contains "$preview_workflow" '.ci/out/e2e/shared-infra-e2e*.json' "preview deploy workflow uploads all shared infra e2e outputs"
  assert_contains "$preview_workflow" 'shared_queue_driver' "preview deploy workflow records queue topology in the release lock"
  assert_contains "$preview_workflow" 'shared_queue_shadow_driver' "preview deploy workflow records queue shadow topology in the release lock"
  assert_contains "$preview_workflow" 'shared_proof_queue_driver' "preview deploy workflow records proof queue topology in the release lock"
  assert_contains "$preview_workflow" 'shared_proof_queue_shadow_driver' "preview deploy workflow records proof queue shadow topology in the release lock"
  assert_contains "$preview_workflow" 'shared_terraform_dir' "preview deploy workflow records shared terraform mode in the release lock"
  assert_contains "$preview_workflow" 'shared_msk_retention_mode' "preview deploy workflow records shared MSK retention mode in the release lock"
  assert_contains "$preview_workflow" 'shared_msk_provisioned' "preview deploy workflow records shared MSK lifecycle state in the release lock"
  assert_contains "$preview_workflow" 'shared_infra_e2e_outputs' "preview deploy workflow records shared infra e2e outputs in the release lock"
  assert_contains "$preview_workflow" 'role-runtime-release-lock.json' "preview deploy workflow publishes a release lock artifact"
  assert_contains "$preview_workflow" 'must not use latest tags' "preview deploy workflow rejects latest tags"

  assert_contains "$reset_preview_workflow" 'operator_stack_ami_release_tag' "preview reset workflow requires the operator stack ami tag"
  assert_contains "$reset_preview_workflow" '--app-binaries-release-tag "${{ inputs.app_binaries_release_tag }}"' "preview reset workflow refreshes app runtime from the selected app-binaries release"
  assert_contains "$reset_preview_workflow" 'upgrade-preview-inventory.sh' "preview reset workflow upgrades legacy preview inputs into the role runtime contract"
  assert_contains "$reset_preview_workflow" 'destroy-preview-role-runtime.sh' "preview reset workflow destroys the current preview role runtime before rebuild"
  assert_contains "$reset_preview_workflow" 'roll-preview-operators.sh' "preview reset workflow refreshes operators after the shared and app rebuild"
  assert_contains "$reset_preview_workflow" 'shared-infra-e2e_linux_amd64' "preview reset workflow downloads the released shared-infra-e2e binary"
  assert_contains "$reset_preview_workflow" '.ci/preview-reset-output/preview/e2e/shared-infra-e2e*.json' "preview reset workflow uploads all shared infra e2e outputs"
  assert_contains "$reset_preview_workflow" 'role-runtime-release-lock.json' "preview reset workflow publishes a release lock artifact"
  assert_contains "$reset_preview_workflow" 'must not use latest tags' "preview reset workflow rejects latest tags"
  assert_contains "$reset_preview_workflow" 'PREVIEW_BRIDGE_FUNDER_KEY' "preview reset workflow uses the preview bridge funder secret for ephemeral bridge deployment"
  assert_contains "$reset_preview_workflow" 'PREVIEW_BRIDGE_EPHEMERAL_FUNDING_AMOUNT_WEI' "preview reset workflow requires an explicit preview bridge ephemeral funding amount"

  assert_contains "$mainnet_workflow" 'preview_run_id' "mainnet deploy workflow requires the preview workflow run id"
  assert_contains "$mainnet_workflow" 'environment: production' "mainnet deploy workflow is gated by the production environment"
  assert_contains "$mainnet_workflow" 'role-runtime-release-lock.json' "mainnet deploy workflow reads the preview release lock artifact"
  assert_contains "$mainnet_workflow" '86400' "mainnet deploy workflow enforces a 24 hour preview soak"
  assert_contains "$mainnet_workflow" 'reset-preview-role-runtime' "mainnet deploy workflow accepts the reset preview workflow as the promotion source"
  assert_contains "$mainnet_workflow" '.operator_stack_ami_release_tag // empty' "mainnet deploy workflow compares the previewed operator stack ami tag"
  assert_contains "$mainnet_workflow" 'Verify Preview Queue Topology' "mainnet deploy workflow gates promotion on preview queue topology"
  assert_contains "$mainnet_workflow" 'shared_infra_e2e_outputs' "mainnet deploy workflow verifies preview shared infra e2e outputs"
  assert_contains "$mainnet_workflow" 'shared-infra-e2e.kafka-shadow.json' "mainnet deploy workflow requires kafka shadow e2e proof when kafka remains active"
  assert_contains "$mainnet_workflow" 'shared-infra-e2e.postgres-shadow.json' "mainnet deploy workflow requires postgres shadow e2e proof when postgres remains active"
  assert_contains "$mainnet_workflow" 'preview shared terraform dir mismatch' "mainnet deploy workflow compares shared terraform mode"
  assert_contains "$mainnet_workflow" 'shared MSK retention mode' "mainnet deploy workflow compares shared MSK retention mode"
  assert_contains "$mainnet_workflow" 'shared MSK provisioned state' "mainnet deploy workflow compares shared MSK provisioned state"
  assert_contains "$mainnet_workflow" 'operator_stack_ami_release_tag promotion requires reset-preview-role-runtime' "mainnet deploy workflow requires reset preview for operator AMI promotions"
  assert_contains "$mainnet_workflow" 'queue topology promotion requires reset-preview-role-runtime' "mainnet deploy workflow requires reset preview for queue topology promotions"
  assert_contains "$mainnet_workflow" 'resolve-role-runtime-release-inputs.sh' "mainnet deploy workflow resolves pinned role runtime release manifests"
  assert_contains "$mainnet_workflow" 'deploy-coordinator.sh' "mainnet deploy workflow drives the production coordinator"
  assert_contains "$mainnet_workflow" '--app-binaries-release-tag "${{ inputs.app_binaries_release_tag }}"' "mainnet deploy workflow refreshes app runtime from the selected app-binaries release"
  assert_contains "$mainnet_workflow" 'must not use latest tags' "mainnet deploy workflow rejects latest tags"
}

main "$@"
