#!/usr/bin/env bash
# shellcheck shell=bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
source "$REPO_ROOT/deploy/production/tests/common_test.sh"

assert_not_contains() {
  local haystack="$1"
  local needle="$2"
  local msg="$3"
  if [[ "$haystack" == *"$needle"* ]]; then
    printf 'assert_not_contains failed: %s: found=%q\n' "$msg" "$needle" >&2
    exit 1
  fi
}

main() {
  local main_tf variables_tf monitoring_tf outputs_tf versions_tf restore_runbook
  local operator_launch_template_block
  main_tf="$(cat "$SCRIPT_DIR/main.tf")"
  variables_tf="$(cat "$SCRIPT_DIR/variables.tf")"
  monitoring_tf="$(cat "$SCRIPT_DIR/monitoring.tf")"
  outputs_tf="$(cat "$SCRIPT_DIR/outputs.tf")"
  versions_tf="$(cat "$SCRIPT_DIR/versions.tf")"
  restore_runbook="$(cat "$REPO_ROOT/deploy/shared/runbooks/aurora-dr-restore.md")"
  operator_launch_template_block="$(awk '/resource "aws_launch_template" "operator" {/,/^}/' "$SCRIPT_DIR/main.tf")"

  assert_contains "$versions_tf" 'backend "s3" {}' "live-e2e declares an s3 backend block for coordinator bootstrap"
  assert_contains "$variables_tf" 'variable "shared_sp1_funder_secret_arn"' "live-e2e exposes distinct proof funder secret input"
  assert_contains "$variables_tf" 'variable "shared_sp1_requestor_address"' "live-e2e exposes shared proof requestor address input"
  assert_contains "$variables_tf" 'variable "shared_base_chain_id"' "live-e2e exposes base chain id input for proof request IDs"
  assert_contains "$variables_tf" 'variable "shared_deposit_image_id"' "live-e2e exposes deposit image id input"
  assert_contains "$variables_tf" 'variable "shared_withdraw_image_id"' "live-e2e exposes withdraw image id input"
  assert_contains "$variables_tf" 'variable "shared_ipfs_data_volume_size_gb"' "live-e2e exposes dedicated IPFS data volume sizing"
  assert_contains "$variables_tf" 'variable "shared_wireguard_enabled"' "live-e2e exposes the preview wireguard toggle"
  assert_contains "$variables_tf" 'variable "shared_wireguard_public_subnet_id"' "live-e2e exposes an optional dedicated wireguard public subnet input"
  assert_contains "$variables_tf" 'variable "shared_wireguard_backoffice_private_endpoint"' "live-e2e exposes an optional private backoffice endpoint override"
  assert_contains "$variables_tf" 'variable "shared_wireguard_backoffice_hostname"' "live-e2e exposes the vpn backoffice hostname input"
  assert_contains "$variables_tf" 'variable "shared_existing_vpc_endpoint_services"' "live-e2e accepts a generated list of reusable VPC endpoints"
  assert_contains "$main_tf" 'runner_private_ip              = cidrhost(data.aws_subnet.selected.cidr_block, 10)' "live-e2e pins the runner to a stable private ip"
  assert_contains "$main_tf" 'resource "aws_instance" "wireguard_gateway"' "live-e2e provisions a dedicated wireguard gateway instance"
  assert_not_contains "$main_tf" 'wireguard_gateway_private_ip = local.wireguard_enabled ? cidrhost(data.aws_subnet.wireguard_public[0].cidr_block, 11) : ""' "live-e2e no longer pins the wireguard gateway to a reused subnet ip"
  assert_not_contains "$main_tf" 'private_ip                  = local.wireguard_gateway_private_ip' "live-e2e lets aws allocate the wireguard gateway private ip"
  assert_contains "$main_tf" 'user_data_replace_on_change = true' "live-e2e replaces the wireguard gateway when its bootstrap config changes"
  assert_contains "$main_tf" 'instance_refresh {' "live-e2e rolls operator autoscaling instances when the launch template changes"
  assert_contains "$main_tf" 'triggers = ["launch_template"]' "live-e2e ties operator instance refreshes to launch template updates"
  assert_contains "$main_tf" "rm -f /etc/dnsmasq.d/intents-juno-wireguard.conf.*" "live-e2e removes stale wireguard dnsmasq backup files before restart"
  assert_contains "$variables_tf" $'variable "shared_ecs_desired_count" {\n  description = "Desired task count for each shared proof service ECS service (proof-requestor and proof-funder)."\n  type        = number\n  default     = 1' "live-e2e enables proof services by default"
  assert_contains "$variables_tf" 'If empty, the first two private subnets in distinct AZs in the selected VPC are used.' "live-e2e documents private shared subnet auto-selection"
  assert_contains "$variables_tf" $'variable "runner_associate_public_ip_address" {\n  description = "Whether to associate a public IPv4 address to the runner EC2 instance."\n  type        = bool\n  default     = true' "live-e2e defaults the runner to a public IPv4 address"
  assert_contains "$variables_tf" $'variable "operator_associate_public_ip_address" {\n  description = "Whether to associate public IPv4 addresses to operator EC2 instances."\n  type        = bool\n  default     = true' "live-e2e defaults operators to public IPv4 addresses"
  assert_contains "$variables_tf" 'variable "operator_client_security_group_ids"' "live-e2e exposes additional operator client security groups"
  assert_contains "$variables_tf" 'variable "shared_service_client_security_group_ids"' "live-e2e exposes additional shared service client security groups"
  assert_contains "$variables_tf" 'variable "shared_ipfs_client_security_group_ids"' "live-e2e exposes additional ipfs client security groups"
  assert_contains "$variables_tf" $'variable "shared_kafka_port" {\n  description = "MSK SASL/IAM bootstrap port exposed to clients."\n  type        = number\n  default     = 9098' "live-e2e defaults kafka port to the MSK IAM listener"
  assert_contains "$variables_tf" 'shared_kafka_port must be 9098 for MSK IAM bootstrap brokers.' "live-e2e validates the IAM kafka listener port"
  assert_contains "$variables_tf" $'variable "shared_msk_broker_instance_type" {\n  description = "MSK broker instance type."\n  type        = string\n  default     = "kafka.m5.large"' "live-e2e defaults MSK to an IAM-ready broker class"
  assert_contains "$main_tf" 'description = "HTTPS for bridge origin and direct app access"' "live-e2e keeps runner https ingress durable for the bridge edge origin"
  assert_contains "$main_tf" $'from_port   = 443\n    to_port     = 443\n    protocol    = "tcp"\n    cidr_blocks = ["0.0.0.0/0"]' "live-e2e runner sg exposes https publicly for edge/origin reachability"
  assert_contains "$main_tf" $'allowed_checkpoint_signer_kms_key_arns = sort(distinct(concat(\n    [aws_kms_key.dkg.arn],' "live-e2e auto-includes the managed dkg kms key in checkpoint signer allowlists"
  assert_contains "$main_tf" 'Sid    = "AllowCheckpointSignerKMS"' "live-e2e always renders checkpoint signer kms permissions"
  assert_contains "$main_tf" '"kms:DescribeKey"' "live-e2e checkpoint signer kms policy allows restore preflight DescribeKey"
  assert_contains "$main_tf" 'Resource = local.allowed_checkpoint_signer_kms_key_arns' "live-e2e checkpoint signer kms policy uses the full allowlist"
  assert_not_contains "$main_tf" 'for_each = length(local.allowed_checkpoint_signer_kms_key_arns) > 0 ? [1] : []' "live-e2e no longer hides checkpoint signer kms permissions behind a dynamic block"
  assert_contains "$main_tf" 'shared_kafka_cluster_arn           = length(aws_msk_cluster.shared) > 0 ? aws_msk_cluster.shared[0].arn : ""' "live-e2e guards the shared kafka cluster arn when the MSK resource tuple is empty"
  assert_contains "$main_tf" 'shared_kafka_topic_arn_prefix      = replace(local.shared_kafka_cluster_arn, ":cluster/", ":topic/")' "live-e2e derives kafka topic arns from the guarded MSK cluster arn"
  assert_contains "$main_tf" 'shared_kafka_group_arn_prefix      = replace(local.shared_kafka_cluster_arn, ":cluster/", ":group/")' "live-e2e derives kafka group arns from the guarded MSK cluster arn"
  assert_contains "$main_tf" 'Sid    = "AllowSharedMSKConnect"' "live-e2e runner/operator role grants MSK cluster auth permissions"
  assert_contains "$main_tf" '"kafka-cluster:Connect"' "live-e2e runner/operator role can connect to MSK"
  assert_contains "$main_tf" 'Resource = [local.shared_kafka_cluster_arn]' "live-e2e runner/operator role reuses the guarded MSK cluster arn in shared access policies"
  assert_contains "$main_tf" 'Sid    = "AllowSharedMSKTopicAccess"' "live-e2e runner/operator role grants MSK topic permissions"
  assert_contains "$main_tf" '"kafka-cluster:CreateTopic"' "live-e2e runner/operator role can bootstrap required Kafka topics"
  assert_contains "$main_tf" '"kafka-cluster:DescribeTopicDynamicConfiguration"' "live-e2e runner/operator role can inspect Kafka topic configuration during bootstrap"
  assert_contains "$main_tf" '"kafka-cluster:AlterTopic"' "live-e2e runner/operator role can reconcile Kafka topic configuration during bootstrap"
  assert_contains "$main_tf" '"kafka-cluster:WriteDataIdempotently"' "live-e2e runner/operator role can use idempotent Kafka writes during bootstrap"
  assert_contains "$main_tf" '["${local.shared_kafka_topic_arn_prefix}/*"]' "live-e2e runner/operator role scopes topic access to the shared cluster"
  assert_contains "$main_tf" 'Sid    = "AllowSharedMSKGroupAccess"' "live-e2e runner/operator role grants MSK consumer group permissions"
  assert_contains "$main_tf" '["${local.shared_kafka_group_arn_prefix}/*"]' "live-e2e runner/operator role scopes group access to the shared cluster"
  assert_contains "$main_tf" 'client_authentication {' "live-e2e enables explicit MSK client authentication"
  assert_contains "$main_tf" 'iam = true' "live-e2e enables MSK IAM auth"
  assert_contains "$main_tf" 'connectivity_info {' "live-e2e configures explicit MSK broker connectivity"
  assert_contains "$main_tf" 'vpc_connectivity {' "live-e2e enables explicit VPC connectivity settings for MSK"
  assert_contains "$main_tf" 'client_authentication {' "live-e2e renders VPC connectivity auth settings"
  assert_contains "$main_tf" 'sasl {' "live-e2e renders VPC connectivity SASL settings"
  assert_contains "$main_tf" 'iam = true' "live-e2e enables IAM auth on VPC-connected brokers"
  assert_contains "$main_tf" 'shared_kafka_bootstrap_brokers     = length(aws_msk_cluster.shared) > 0 ? aws_msk_cluster.shared[0].bootstrap_brokers_sasl_iam : ""' "live-e2e shared services consume IAM bootstrap brokers even when the MSK tuple is empty"
  assert_not_contains "$main_tf" 'shared_kafka_bootstrap_brokers_tls = try(aws_msk_cluster.shared[0].bootstrap_brokers_tls, "")' "live-e2e no longer routes shared services through TLS-only brokers"
  assert_contains "$main_tf" 'shared_kafka_topic_arn_prefix' "live-e2e derives kafka topic arn prefixes for IAM auth"
  assert_contains "$main_tf" 'replace(local.shared_kafka_cluster_arn, ":cluster/", ":topic/")' "live-e2e topic arn prefixes tolerate disabled shared services"
  assert_contains "$main_tf" 'shared_kafka_group_arn_prefix' "live-e2e derives kafka consumer group arn prefixes for IAM auth"
  assert_contains "$main_tf" 'replace(local.shared_kafka_cluster_arn, ":cluster/", ":group/")' "live-e2e group arn prefixes tolerate disabled shared services"
  assert_contains "$main_tf" 'resource "aws_iam_role" "proof_requestor_task"' "live-e2e provisions a proof-requestor task role"
  assert_contains "$main_tf" 'resource "aws_iam_role" "proof_funder_task"' "live-e2e provisions a proof-funder task role"
  assert_contains "$main_tf" 'resource "aws_iam_role_policy" "proof_requestor_task_access"' "live-e2e provisions proof-requestor kafka task access"
  assert_contains "$main_tf" 'resource "aws_iam_role_policy" "proof_funder_task_access"' "live-e2e provisions proof-funder kafka task access"
  assert_contains "$main_tf" 'sid = "AllowMSKTopicAccess"' "live-e2e proof-requestor task role grants broad kafka topic access"
  assert_contains "$main_tf" 'sid = "AllowMSKGroupAccess"' "live-e2e proof-requestor task role grants broad kafka group access"
  assert_contains "$main_tf" '"kafka-cluster:DescribeTopicDynamicConfiguration"' "live-e2e proof-requestor task role can inspect kafka topic configuration"
  assert_contains "$main_tf" '"kafka-cluster:WriteDataIdempotently"' "live-e2e proof-requestor task role supports idempotent kafka writes"
  assert_contains "$main_tf" 'resources = ["${local.shared_kafka_topic_arn_prefix}/*"]' "live-e2e proof-requestor task role scopes topic access to the shared cluster"
  assert_contains "$main_tf" 'resources = ["${local.shared_kafka_group_arn_prefix}/*"]' "live-e2e proof-requestor task role scopes group access to the shared cluster"
  assert_contains "$main_tf" 'resource "aws_secretsmanager_secret" "shared_ipfs_api_bearer_token"' "live-e2e provisions a dedicated IPFS API bearer token secret"
  assert_contains "$main_tf" 'for attempt in $(seq 1 30); do' "live-e2e retries ipfs bearer token fetches during first boot"
  assert_contains "$main_tf" 'sleep 5' "live-e2e backs off between ipfs bearer token fetch retries"
  assert_contains "$main_tf" '/usr/local/bin/bootstrap-shared-ipfs.sh' "live-e2e renders a dedicated ipfs bootstrap helper"
  assert_contains "$main_tf" 'ExecStart=/usr/local/bin/bootstrap-shared-ipfs.sh' "live-e2e runs the ipfs bootstrap through systemd"
  assert_contains "$main_tf" 'Restart=on-failure' "live-e2e keeps retrying ipfs bootstrap after transient first-boot failures"
  assert_contains "$main_tf" 'systemctl enable --now intents-shared-ipfs-bootstrap.service' "live-e2e enables the ipfs bootstrap unit during first boot"
  assert_contains "$main_tf" 'shared ipfs api bearer token unavailable' "live-e2e fails with a clear ipfs bootstrap error after retry exhaustion"
  assert_contains "$main_tf" 'resource "aws_secretsmanager_secret" "shared_kafka_critical_hmac_key"' "live-e2e provisions a dedicated Kafka critical-topic HMAC secret"
  assert_contains "$main_tf" 'resource "aws_security_group" "wireguard"' "live-e2e provisions a dedicated wireguard security group"
  assert_contains "$main_tf" 'resource "aws_instance" "wireguard_gateway"' "live-e2e provisions a dedicated wireguard gateway instance"
  assert_contains "$main_tf" 'resource "aws_eip" "wireguard_gateway"' "live-e2e provisions a stable public endpoint for wireguard"
  assert_contains "$main_tf" 'resource "aws_secretsmanager_secret" "shared_wireguard_client_config"' "live-e2e provisions a secret for the backoffice wireguard client config"
  assert_contains "$main_tf" 'source_dest_check           = false' "live-e2e disables source destination checks on the wireguard gateway"
  assert_contains "$main_tf" 'resource "aws_iam_instance_profile" "wireguard_gateway"' "live-e2e provisions a wireguard gateway instance profile"
  assert_contains "$main_tf" 'wg genkey' "live-e2e bootstraps wireguard peers on first boot"
  assert_contains "$main_tf" '"ec2:DescribeInstances"' "live-e2e grants the wireguard gateway permission to look up its elastic ip association"
  assert_contains "$main_tf" 'instance_id="$(curl -fsS -H "X-aws-ec2-metadata-token: $imds_token" http://169.254.169.254/latest/meta-data/instance-id)"' "live-e2e records the wireguard instance id during bootstrap"
  assert_contains "$main_tf" "aws --region \${var.aws_region} ec2 describe-instances --instance-ids \"\$instance_id\"" "live-e2e waits for the elastic ip to appear via ec2 instead of relying on early imds public-ipv4"
  assert_contains "$main_tf" 'address=/${var.shared_wireguard_backoffice_hostname}/$${wireguard_backoffice_private_endpoint}' "live-e2e maps the backoffice hostname to the private app endpoint over wireguard"
  assert_contains "$main_tf" 'iptables -A FORWARD -i %i -j ACCEPT' "live-e2e allows forwarded traffic from the wireguard tunnel"
  assert_contains "$main_tf" 'iptables -A FORWARD -o %i -j ACCEPT' "live-e2e allows forwarded return traffic to the wireguard tunnel"
  assert_contains "$main_tf" 'secretsmanager put-secret-value --secret-id "$wireguard_client_config_secret_arn"' "live-e2e uploads the generated wireguard client config into Secrets Manager"
  local wg_restart_line
  local dnsmasq_restart_line
  wg_restart_line="$(printf '%s\n' "$main_tf" | grep -n 'systemctl restart wg-quick@wg0' | cut -d: -f1)"
  dnsmasq_restart_line="$(printf '%s\n' "$main_tf" | grep -n 'systemctl restart dnsmasq' | cut -d: -f1)"
  if (( dnsmasq_restart_line <= wg_restart_line )); then
    printf 'wireguard ordering assertion failed: live-e2e must start wg0 before dnsmasq (wg=%s dns=%s)\n' "$wg_restart_line" "$dnsmasq_restart_line" >&2
    exit 1
  fi
  assert_contains "$main_tf" 'Sid    = "AllowSharedIPFSSecretRead"' "live-e2e runner/operator role can read the shared IPFS bearer token secret"
  assert_contains "$main_tf" 'resource "aws_iam_role_policy_attachment" "live_e2e_ssm_managed_instance_core"' "live-e2e attaches SSM managed instance core to the shared instance role"
  assert_contains "$main_tf" 'policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"' "live-e2e uses the AWS-managed SSM instance core policy"
  assert_contains "$main_tf" '"kafka-cluster:Connect"' "live-e2e grants kafka connect permissions to proof task roles"
  assert_contains "$main_tf" 'resources = [local.shared_kafka_cluster_arn]' "live-e2e proof task roles re-use the guarded MSK cluster arn"

  assert_contains "$main_tf" '"/usr/local/bin/proof-requestor"' "live-e2e requestor still launches proof-requestor binary"
  assert_contains "$main_tf" '"--postgres-dsn"' "live-e2e requestor command includes postgres dsn"
  assert_contains "$main_tf" '"--owner"' "live-e2e requestor command includes owner"
  assert_contains "$main_tf" '"--sp1-requestor-address"' "live-e2e requestor command includes requestor address"
  assert_contains "$main_tf" '"--sp1-requestor-key-secret-arn"' "live-e2e requestor command includes requestor key reference"
  assert_contains "$main_tf" '"--chain-id"' "live-e2e requestor command includes chain id"
  assert_contains "$main_tf" '"--queue-brokers"' "live-e2e requestor command includes kafka brokers"
  assert_contains "$main_tf" 'local.shared_kafka_bootstrap_brokers,' "live-e2e proof tasks use IAM kafka brokers"
  assert_contains "$main_tf" '"--sp1-bin"' "live-e2e requestor command includes prover adapter binary"
  assert_contains "$main_tf" 'name      = "PROOF_REQUESTOR_KEY"' "live-e2e requestor task keeps requestor secret name"
  assert_contains "$main_tf" 'task_role_arn            = aws_iam_role.proof_requestor_task[0].arn' "live-e2e requestor task definition uses the proof-requestor task role"

  assert_contains "$main_tf" '"/usr/local/bin/proof-funder"' "live-e2e funder still launches proof-funder binary"
  assert_contains "$main_tf" '"--owner-id"' "live-e2e funder command includes owner id"
  assert_contains "$main_tf" '"--min-balance-wei"' "live-e2e funder command includes minimum balance threshold"
  assert_contains "$main_tf" '"--critical-balance-wei"' "live-e2e funder command includes critical balance threshold"
  assert_contains "$main_tf" 'name      = "PROOF_FUNDER_KEY"' "live-e2e funder task keeps funder secret name"
  assert_contains "$main_tf" 'valueFrom = local.shared_sp1_funder_secret_arn' "live-e2e funder task uses funder secret ARN"
  assert_contains "$main_tf" 'task_role_arn            = aws_iam_role.proof_funder_task[0].arn' "live-e2e funder task definition uses the proof-funder task role"
  assert_contains "$outputs_tf" 'output "shared_sp1_requestor_address"' "live-e2e exports the shared proof requestor address"
  assert_contains "$outputs_tf" 'trimspace(var.shared_sp1_requestor_address)' "live-e2e output keeps the rendered proof requestor address"
  assert_contains "$outputs_tf" 'output "shared_sp1_rpc_url"' "live-e2e exports the shared succinct rpc url"
  assert_contains "$outputs_tf" 'trimspace(var.shared_sp1_rpc_url)' "live-e2e output keeps the rendered succinct rpc url"
  assert_contains "$outputs_tf" 'output "shared_ipfs_api_auth_secret_arn"' "live-e2e exports the shared IPFS bearer token secret ARN"
  assert_contains "$outputs_tf" 'output "shared_postgres_cluster_arn"' "live-e2e exports the shared aurora cluster arn for preview health checks"
  assert_contains "$outputs_tf" 'try(aws_rds_cluster.shared[0].arn, null)' "live-e2e output guards the shared aurora cluster arn when shared services are disabled"
  assert_contains "$outputs_tf" 'output "shared_kafka_cluster_arn"' "live-e2e exports the shared msk cluster arn for preview health checks"
  assert_contains "$outputs_tf" 'try(aws_msk_cluster.shared[0].arn, null)' "live-e2e output guards the shared msk cluster arn when shared services are disabled"
  assert_contains "$outputs_tf" 'output "shared_ipfs_target_group_arn"' "live-e2e exports the shared ipfs target group arn for preview health checks"
  assert_contains "$outputs_tf" 'try(aws_lb_target_group.ipfs_api[0].arn, null)' "live-e2e output guards the shared ipfs target group arn when shared services are disabled"
  assert_contains "$outputs_tf" 'output "shared_kafka_critical_hmac_secret_arn"' "live-e2e exports the Kafka critical-topic HMAC secret ARN"

  assert_contains "$main_tf" 'name  = "SP1_NETWORK_RPC_URL"' "live-e2e proof task env includes SP1 rpc url"
  assert_contains "$main_tf" 'name  = "JUNO_QUEUE_KAFKA_AUTH_MODE"' "live-e2e proof task env includes kafka auth mode"
  assert_contains "$main_tf" 'value = "aws-msk-iam"' "live-e2e proof task env pins MSK IAM auth"
  assert_contains "$main_tf" 'name  = "JUNO_QUEUE_KAFKA_AWS_REGION"' "live-e2e proof task env includes kafka iam region"
  assert_contains "$main_tf" 'name  = "SP1_DEPOSIT_PROGRAM_URL"' "live-e2e proof task env includes deposit program url"
  assert_contains "$main_tf" 'name  = "SP1_WITHDRAW_PROGRAM_URL"' "live-e2e proof task env includes withdraw program url"
  assert_contains "$main_tf" 'name  = "SP1_DEPOSIT_PROGRAM_VKEY"' "live-e2e proof task env includes deposit vkey"
  assert_contains "$main_tf" 'name  = "SP1_WITHDRAW_PROGRAM_VKEY"' "live-e2e proof task env includes withdraw vkey"

  assert_contains "$variables_tf" 'Required when provision_shared_services is true' "live-e2e documents explicit proof image requirement"
  assert_contains "$main_tf" 'shared_proof_service_image must be set when provision_shared_services=true.' "live-e2e fails closed without explicit proof image"
  assert_contains "$main_tf" 'shared_proof_service_image         = trimspace(var.shared_proof_service_image)' "live-e2e uses explicit proof image input directly"
  assert_not_contains "$main_tf" 'repository_url}:latest' "live-e2e no longer defaults proof services to empty terraform-managed latest tag"
  assert_contains "$main_tf" '!local.shared_proof_runtime_enabled || local.shared_sp1_requestor_address != ""' "live-e2e gates active proof services behind runtime contract"
  assert_contains "$main_tf" 'shared_sp1_requestor_address must be set when shared_ecs_desired_count > 0' "live-e2e blocks active proof services without requestor address"
  assert_contains "$main_tf" 'private_subnets_by_az' "live-e2e derives shared subnets from private subnets only"
  assert_contains "$main_tf" 'if !s.map_public_ip_on_launch' "live-e2e filters public subnets out of shared subnet auto-selection"
  assert_contains "$main_tf" 'public_subnets_by_az' "live-e2e derives runner/operator subnets from public subnets"
  assert_contains "$main_tf" 'if s.map_public_ip_on_launch' "live-e2e filters private subnets out of runner/operator auto-selection"
  assert_contains "$main_tf" 'selected_subnet_id = var.subnet_id != "" ? var.subnet_id : local.public_one_per_az[0]' "live-e2e defaults runner/operator hosts onto a deterministic public subnet"
  assert_not_contains "$main_tf" 'selected_subnet_id = var.subnet_id != "" ? var.subnet_id : data.aws_subnets.selected_vpc.ids[0]' "live-e2e no longer chooses runner/operator subnets from an unordered vpc subnet list"
  assert_contains "$main_tf" 'private_ip             = local.runner_private_ip' "live-e2e assigns the runner a stable private ip"
  assert_contains "$main_tf" 'resource "aws_launch_template" "operator"' "live-e2e provisions operator launch templates"
  assert_contains "$operator_launch_template_block" 'user_data = base64encode(<<-EOF' "live-e2e base64-encodes operator launch template user data for EC2"
  assert_not_contains "$operator_launch_template_block" 'user_data = <<-EOF' "live-e2e does not leave operator launch template user data unencoded"
  assert_contains "$main_tf" 'device_name = "/dev/sda1"' "live-e2e operator launch templates map the root volume through block_device_mappings"
  assert_contains "$main_tf" 'resource "aws_autoscaling_group" "operator"' "live-e2e provisions one autoscaling group per operator"
  assert_not_contains "$main_tf" 'resource "aws_instance" "operator"' "live-e2e no longer provisions bare operator instances"
  assert_contains "$main_tf" 'desired_capacity    = 1' "live-e2e pins each operator asg to a single live instance"
  assert_contains "$main_tf" 'min_size            = 1' "live-e2e keeps each operator asg at min size one"
  assert_contains "$main_tf" 'max_size            = 1' "live-e2e keeps each operator asg at max size one"
  assert_contains "$main_tf" 'vpc_zone_identifier = var.subnet_id != "" ? [var.subnet_id] : local.public_one_per_az' "live-e2e lets operator asgs replace instances across the public subnet set"
  assert_contains "$main_tf" 'data "aws_instances" "operator"' "live-e2e resolves operator instance ids from autoscaling groups"
  assert_contains "$main_tf" 'data "aws_instance" "operator"' "live-e2e resolves live operator instance metadata from autoscaling groups"
  assert_contains "$outputs_tf" 'value       = data.aws_instance.operator[*].id' "live-e2e outputs operator instance ids from autoscaling-backed instances"
  assert_contains "$outputs_tf" 'value       = data.aws_instance.operator[*].public_ip' "live-e2e outputs operator public ips from autoscaling-backed instances"
  assert_contains "$outputs_tf" 'value       = data.aws_instance.operator[*].private_ip' "live-e2e outputs operator private ips from autoscaling-backed instances"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "operator_in_service"' "live-e2e alarms on operator asg in-service capacity"
  assert_contains "$monitoring_tf" 'metric_name         = "GroupInServiceInstances"' "live-e2e monitors operator in-service instance count"
  assert_contains "$monitoring_tf" 'namespace           = "AWS/AutoScaling"' "live-e2e uses autoscaling metrics for operator health"
  assert_contains "$monitoring_tf" 'AutoScalingGroupName = aws_autoscaling_group.operator[count.index].name' "live-e2e scopes operator alarms to each asg"
  assert_not_contains "$monitoring_tf" 'InstanceId = aws_instance.operator[count.index].id' "live-e2e no longer pins operator alarms to a single bare instance id"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "mark_paid_circuit_open"' "live-e2e alarms on the withdraw mark-paid circuit breaker"
  assert_contains "$monitoring_tf" 'metric_name         = "MarkPaidCircuitOpen"' "live-e2e wires the mark-paid circuit metric name"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "deposit_proof_requested_count"' "live-e2e alarms on stuck deposit proof requests"
  assert_contains "$monitoring_tf" 'metric_name         = "DepositProofRequestedCount"' "live-e2e wires the deposit proof-requested metric name"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "deposit_submitted_count"' "live-e2e alarms on stuck submitted deposits"
  assert_contains "$monitoring_tf" 'metric_name         = "DepositSubmittedCount"' "live-e2e wires the deposit submitted metric name"
  assert_contains "$main_tf" 'description     = "Juno RPC from runner"' "live-e2e permits runner access to operator Juno RPC for backoffice MPC balance reads"
  assert_contains "$main_tf" 'from_port       = 18232' "live-e2e pins operator Juno RPC ingress to port 18232"
  assert_contains "$main_tf" 'to_port         = 18232' "live-e2e exposes only the operator Juno RPC port to the runner"
  assert_contains "$main_tf" 'security_groups = concat([aws_security_group.runner.id], var.operator_client_security_group_ids)' "live-e2e lets app-role security groups share operator ingress with the runner"
  assert_contains "$main_tf" 'description = "Postgres from runner"' "live-e2e exposes shared postgres to runner-class clients"
  assert_contains "$main_tf" 'description = "Kafka from runner"' "live-e2e exposes shared kafka to runner-class clients"
  assert_contains "$main_tf" 'concat([' "live-e2e uses concat-based security group lists where preview app clients are injected"
  assert_contains "$main_tf" 'try(aws_security_group.ecs[0].id, "")' "live-e2e keeps the shared ECS clients on shared service ingress"
  assert_contains "$main_tf" 'var.shared_service_client_security_group_ids' "live-e2e threads additional preview app client security groups into shared postgres and kafka ingress"
  assert_contains "$main_tf" 'concat([aws_security_group.runner.id, aws_security_group.operator.id], var.shared_ipfs_client_security_group_ids)' "live-e2e threads additional preview app client security groups into ipfs ingress"
  assert_contains "$main_tf" 'check "shared_ecs_private_subnets_when_no_public_ip"' "live-e2e guards shared ECS subnet/public-ip compatibility"
  assert_contains "$main_tf" 'shared proof services require private shared_subnet_ids when shared_ecs_assign_public_ip=false.' "live-e2e fails closed on public shared subnets without public IPs"
  assert_contains "$main_tf" 'data "aws_route_table" "shared"' "live-e2e resolves route tables for shared subnets"
  assert_contains "$main_tf" 'resource "aws_security_group" "shared_vpc_endpoints"' "live-e2e provisions a dedicated security group for interface endpoints"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "secretsmanager"' "live-e2e provisions a Secrets Manager VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "ecr_api"' "live-e2e provisions an ECR API VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "ecr_dkr"' "live-e2e provisions an ECR DKR VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "sts"' "live-e2e provisions an STS VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "kms"' "live-e2e provisions a KMS VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "logs"' "live-e2e provisions a CloudWatch Logs VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "s3"' "live-e2e provisions an S3 gateway endpoint"
  assert_not_contains "$main_tf" 'data "aws_vpc_endpoints"' "live-e2e no longer relies on unsupported plural VPC endpoint data sources"
  assert_contains "$main_tf" 'existing_vpc_endpoint_services = sort(distinct([' "live-e2e normalizes the generated reusable VPC endpoint services list"
  assert_contains "$main_tf" 'count = var.provision_shared_services && !contains(local.existing_vpc_endpoint_services, "com.amazonaws.${var.aws_region}.secretsmanager") ? 1 : 0' "live-e2e skips Secrets Manager endpoint creation when the VPC already has one"
  assert_contains "$main_tf" 'count = var.provision_shared_services && !contains(local.existing_vpc_endpoint_services, "com.amazonaws.${var.aws_region}.s3") ? 1 : 0' "live-e2e skips S3 gateway endpoint creation when the VPC already has one"
  assert_contains "$main_tf" 'count = var.provision_shared_services && !contains(local.existing_vpc_endpoint_services, "com.amazonaws.${var.aws_region}.secretsmanager") ? 1 : 0' "live-e2e skips creating a duplicate Secrets Manager endpoint when the reused preview VPC already has one"
  assert_contains "$main_tf" 'count = var.provision_shared_services && !contains(local.existing_vpc_endpoint_services, "com.amazonaws.${var.aws_region}.s3") ? 1 : 0' "live-e2e skips creating a duplicate S3 gateway endpoint when the reused preview VPC already has one"
  assert_contains "$main_tf" 'description = "HTTPS from the VPC"' "live-e2e opens interface endpoints to the whole preview VPC"
  assert_contains "$main_tf" 'cidr_blocks = [data.aws_vpc.selected.cidr_block]' "live-e2e interface endpoints allow operator and runner subnets"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.secretsmanager"' "live-e2e points the Secrets Manager endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.ecr.api"' "live-e2e points the ECR API endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.ecr.dkr"' "live-e2e points the ECR DKR endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.sts"' "live-e2e points the STS endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.kms"' "live-e2e points the KMS endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.logs"' "live-e2e points the CloudWatch Logs endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name      = "com.amazonaws.${var.aws_region}.s3"' "live-e2e points the S3 endpoint at the deployment region"
  assert_contains "$main_tf" 'route_table_ids   = local.shared_route_table_ids' "live-e2e attaches the S3 gateway endpoint to the shared route tables"
  assert_contains "$main_tf" 'security_group_ids  = [aws_security_group.shared_vpc_endpoints[0].id]' "live-e2e constrains interface endpoints behind the dedicated SG"
  assert_contains "$main_tf" 'private_dns_enabled = true' "live-e2e enables private DNS on interface endpoints"
  assert_contains "$main_tf" 'volume_size           = var.shared_ipfs_data_volume_size_gb' "live-e2e provisions a dedicated IPFS data volume"
  assert_contains "$main_tf" 'delete_on_termination = false' "live-e2e preserves the dedicated IPFS data volume across instance replacement"
  assert_contains "$main_tf" '/var/lib/intents-juno/ipfs' "live-e2e mounts a dedicated IPFS data path"
  assert_contains "$main_tf" 'enable_cross_zone_load_balancing = true' "live-e2e enables cross-zone load balancing on the IPFS NLB"
  assert_not_contains "$main_tf" 'apt-get install -y awscli' "live-e2e no longer depends on the missing Ubuntu awscli package for IPFS bootstrap"
  assert_contains "$main_tf" 'arch="$(uname -m)"' "live-e2e detects the IPFS instance architecture before installing AWS CLI"
  assert_contains "$main_tf" 'awscli-exe-linux-$${awscli_arch}.zip' "live-e2e installs AWS CLI from the official architecture-specific bundle"
  assert_contains "$main_tf" '/tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update' "live-e2e installs AWS CLI v2 into a stable location"
  assert_contains "$main_tf" 'secretsmanager get-secret-value --secret-id "$ipfs_api_secret_arn"' "live-e2e bootstraps the IPFS bearer token from Secrets Manager"
  assert_contains "$main_tf" 'proxy_pass http://127.0.0.1:5001;' "live-e2e proxies authenticated IPFS API traffic to loopback Kubo"
  assert_contains "$main_tf" 'daemon --migrate=true --api /ip4/127.0.0.1/tcp/5001 --routing=dhtclient' "live-e2e binds raw Kubo API to loopback only"
  assert_not_contains "$main_tf" '--api /ip4/0.0.0.0/tcp/5001' "live-e2e no longer exposes raw Kubo on all interfaces"
  assert_contains "$main_tf" 'alias  = "dr"' "live-e2e configures an aws dr provider alias"
  assert_contains "$variables_tf" 'variable "shared_postgres_dr_region"' "live-e2e exposes the Aurora DR backup region"
  assert_not_contains "$variables_tf" 'trimspace(var.shared_postgres_dr_region) != trimspace(var.aws_region)' "live-e2e no longer uses cross-variable validation in shared_postgres_dr_region"
  assert_contains "$main_tf" 'resource "aws_backup_vault" "shared_postgres"' "live-e2e provisions a primary backup vault"
  assert_contains "$main_tf" 'resource "aws_backup_vault" "shared_postgres_dr"' "live-e2e provisions a DR backup vault"
  assert_contains "$main_tf" 'provider = aws.dr' "live-e2e binds DR backup resources to the dr provider"
  assert_contains "$main_tf" 'resource "aws_backup_plan" "shared_postgres"' "live-e2e provisions an Aurora backup plan"
  assert_contains "$main_tf" 'copy_action {' "live-e2e copies backups into the DR vault"
  assert_contains "$main_tf" 'destination_vault_arn = aws_backup_vault.shared_postgres_dr[0].arn' "live-e2e targets the DR backup vault"
  assert_contains "$main_tf" 'resource "aws_backup_selection" "shared_postgres"' "live-e2e selects the Aurora cluster for AWS Backup"
  assert_contains "$main_tf" 'resources    = [aws_rds_cluster.shared[0].arn]' "live-e2e backs up the Aurora cluster ARN"
  assert_contains "$main_tf" 'resource "aws_iam_role" "shared_backup"' "live-e2e provisions a dedicated AWS Backup role"
  assert_contains "$main_tf" 'AWSBackupServiceRolePolicyForBackup' "live-e2e attaches the AWS Backup backup policy"
  assert_contains "$main_tf" 'AWSBackupServiceRolePolicyForRestores' "live-e2e attaches the AWS Backup restore policy"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "shared_postgres_instance_cpu"' "live-e2e monitors Aurora CPU per instance"
  assert_contains "$monitoring_tf" 'var.provision_shared_services ? aws_rds_cluster_instance.shared : {}' "live-e2e derives Aurora CPU alarms from the keyed cluster instances"
  assert_not_contains "$monitoring_tf" 'aws_rds_cluster_instance.shared[0].identifier' "live-e2e no longer indexes keyed Aurora instances numerically"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "withdrawal_dlq_depth"' "live-e2e alarms on withdrawal dlq depth"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "confirmed_unmarked_count"' "live-e2e alarms on confirmed-unmarked withdrawals"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "min_withdrawal_time_to_expiry_seconds"' "live-e2e alarms on withdrawal expiry runway"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "checkpoint_pin_backlog"' "live-e2e alarms on checkpoint pin backlog"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "tss_session_saturation"' "live-e2e alarms on tss session saturation"
  assert_contains "$monitoring_tf" 'metric_name         = "WithdrawalDLQDepth"' "live-e2e wires the withdrawal dlq metric name"
  assert_contains "$monitoring_tf" 'metric_name         = "ConfirmedUnmarkedCount"' "live-e2e wires the confirmed-unmarked metric name"
  assert_contains "$monitoring_tf" 'metric_name         = "MinWithdrawalTimeToExpirySeconds"' "live-e2e wires the withdrawal expiry metric name"
  assert_contains "$monitoring_tf" 'metric_name         = "CheckpointPinBacklog"' "live-e2e wires the checkpoint pin backlog metric name"
  assert_contains "$monitoring_tf" 'metric_name         = "TSSSessionSaturation"' "live-e2e wires the tss session saturation metric name"
  assert_contains "$monitoring_tf" 'operations_metric_namespace = "IntentsJuno/Operations"' "live-e2e defines the custom operations metric namespace"
  assert_contains "$monitoring_tf" 'namespace           = local.operations_metric_namespace' "live-e2e uses the custom operations metric namespace"
  assert_contains "$restore_runbook" 'backup list-recovery-points-by-backup-vault' "aurora dr runbook enumerates recovery points"
  assert_contains "$restore_runbook" 'backup start-restore-job' "aurora dr runbook documents restore execution"

  printf 'live_e2e package_a_snapshot_test: PASS\n'
}

main "$@"
