#!/usr/bin/env bash
# shellcheck shell=bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
source "$REPO_ROOT/deploy/production/tests/common_test.sh"

assert_not_contains() {
  local haystack="$1"
  local needle="$2"
  local msg="$3"
  if [[ "$haystack" == *"$needle"* ]]; then
    printf 'assert_not_contains failed: %s: found=%q\n' "$msg" "$needle" >&2
    exit 1
  fi
}

main() {
  local main_tf variables_tf monitoring_tf outputs_tf
  main_tf="$(cat "$SCRIPT_DIR/main.tf")"
  variables_tf="$(cat "$SCRIPT_DIR/variables.tf")"
  monitoring_tf="$(cat "$SCRIPT_DIR/monitoring.tf")"
  outputs_tf="$(cat "$SCRIPT_DIR/outputs.tf")"

  assert_contains "$variables_tf" 'variable "shared_sp1_funder_secret_arn"' "live-e2e exposes distinct proof funder secret input"
  assert_contains "$variables_tf" 'variable "shared_sp1_requestor_address"' "live-e2e exposes shared proof requestor address input"
  assert_contains "$variables_tf" 'variable "shared_base_chain_id"' "live-e2e exposes base chain id input for proof request IDs"
  assert_contains "$variables_tf" 'variable "shared_deposit_image_id"' "live-e2e exposes deposit image id input"
  assert_contains "$variables_tf" 'variable "shared_withdraw_image_id"' "live-e2e exposes withdraw image id input"
  assert_contains "$variables_tf" $'variable "shared_ecs_desired_count" {\n  description = "Desired task count for each shared proof service ECS service (proof-requestor and proof-funder)."\n  type        = number\n  default     = 1' "live-e2e enables proof services by default"
  assert_contains "$variables_tf" 'If empty, the first two private subnets in distinct AZs in the selected VPC are used.' "live-e2e documents private shared subnet auto-selection"
  assert_contains "$variables_tf" $'variable "runner_associate_public_ip_address" {\n  description = "Whether to associate a public IPv4 address to the runner EC2 instance."\n  type        = bool\n  default     = true' "live-e2e defaults the runner to a public IPv4 address"
  assert_contains "$variables_tf" $'variable "operator_associate_public_ip_address" {\n  description = "Whether to associate public IPv4 addresses to operator EC2 instances."\n  type        = bool\n  default     = true' "live-e2e defaults operators to public IPv4 addresses"
  assert_contains "$variables_tf" $'variable "shared_kafka_port" {\n  description = "MSK SASL/IAM bootstrap port exposed to clients."\n  type        = number\n  default     = 9098' "live-e2e defaults kafka port to the MSK IAM listener"
  assert_contains "$variables_tf" 'shared_kafka_port must be 9098 for MSK IAM bootstrap brokers.' "live-e2e validates the IAM kafka listener port"
  assert_contains "$variables_tf" $'variable "shared_msk_broker_instance_type" {\n  description = "MSK broker instance type."\n  type        = string\n  default     = "kafka.m5.large"' "live-e2e defaults MSK to an IAM-ready broker class"
  assert_contains "$main_tf" $'allowed_checkpoint_signer_kms_key_arns = sort(distinct(concat(\n    [aws_kms_key.dkg.arn],' "live-e2e auto-includes the managed dkg kms key in checkpoint signer allowlists"
  assert_contains "$main_tf" 'Sid    = "AllowCheckpointSignerKMS"' "live-e2e always renders checkpoint signer kms permissions"
  assert_contains "$main_tf" '"kms:DescribeKey"' "live-e2e checkpoint signer kms policy allows restore preflight DescribeKey"
  assert_contains "$main_tf" 'Resource = local.allowed_checkpoint_signer_kms_key_arns' "live-e2e checkpoint signer kms policy uses the full allowlist"
  assert_not_contains "$main_tf" 'for_each = length(local.allowed_checkpoint_signer_kms_key_arns) > 0 ? [1] : []' "live-e2e no longer hides checkpoint signer kms permissions behind a dynamic block"
  assert_contains "$main_tf" 'shared_kafka_cluster_arn           = length(aws_msk_cluster.shared) > 0 ? aws_msk_cluster.shared[0].arn : ""' "live-e2e guards the shared kafka cluster arn when the MSK resource tuple is empty"
  assert_contains "$main_tf" 'shared_kafka_topic_arn_prefix      = replace(local.shared_kafka_cluster_arn, ":cluster/", ":topic/")' "live-e2e derives kafka topic arns from the guarded MSK cluster arn"
  assert_contains "$main_tf" 'shared_kafka_group_arn_prefix      = replace(local.shared_kafka_cluster_arn, ":cluster/", ":group/")' "live-e2e derives kafka group arns from the guarded MSK cluster arn"
  assert_contains "$main_tf" 'Sid    = "AllowSharedMSKConnect"' "live-e2e runner/operator role grants MSK cluster auth permissions"
  assert_contains "$main_tf" '"kafka-cluster:Connect"' "live-e2e runner/operator role can connect to MSK"
  assert_contains "$main_tf" 'Resource = [local.shared_kafka_cluster_arn]' "live-e2e runner/operator role reuses the guarded MSK cluster arn in shared access policies"
  assert_contains "$main_tf" 'Sid    = "AllowSharedMSKTopicAccess"' "live-e2e runner/operator role grants MSK topic permissions"
  assert_contains "$main_tf" '"kafka-cluster:CreateTopic"' "live-e2e runner/operator role can bootstrap required Kafka topics"
  assert_contains "$main_tf" '"kafka-cluster:DescribeTopicDynamicConfiguration"' "live-e2e runner/operator role can inspect Kafka topic configuration during bootstrap"
  assert_contains "$main_tf" '"kafka-cluster:AlterTopic"' "live-e2e runner/operator role can reconcile Kafka topic configuration during bootstrap"
  assert_contains "$main_tf" '"kafka-cluster:WriteDataIdempotently"' "live-e2e runner/operator role can use idempotent Kafka writes during bootstrap"
  assert_contains "$main_tf" '["${local.shared_kafka_topic_arn_prefix}/*"]' "live-e2e runner/operator role scopes topic access to the shared cluster"
  assert_contains "$main_tf" 'Sid    = "AllowSharedMSKGroupAccess"' "live-e2e runner/operator role grants MSK consumer group permissions"
  assert_contains "$main_tf" '["${local.shared_kafka_group_arn_prefix}/*"]' "live-e2e runner/operator role scopes group access to the shared cluster"
  assert_contains "$main_tf" 'client_authentication {' "live-e2e enables explicit MSK client authentication"
  assert_contains "$main_tf" 'iam = true' "live-e2e enables MSK IAM auth"
  assert_contains "$main_tf" 'connectivity_info {' "live-e2e configures explicit MSK broker connectivity"
  assert_contains "$main_tf" 'vpc_connectivity {' "live-e2e enables explicit VPC connectivity settings for MSK"
  assert_contains "$main_tf" 'client_authentication {' "live-e2e renders VPC connectivity auth settings"
  assert_contains "$main_tf" 'sasl {' "live-e2e renders VPC connectivity SASL settings"
  assert_contains "$main_tf" 'iam = true' "live-e2e enables IAM auth on VPC-connected brokers"
  assert_contains "$main_tf" 'shared_kafka_bootstrap_brokers     = length(aws_msk_cluster.shared) > 0 ? aws_msk_cluster.shared[0].bootstrap_brokers_sasl_iam : ""' "live-e2e shared services consume IAM bootstrap brokers even when the MSK tuple is empty"
  assert_not_contains "$main_tf" 'shared_kafka_bootstrap_brokers_tls = try(aws_msk_cluster.shared[0].bootstrap_brokers_tls, "")' "live-e2e no longer routes shared services through TLS-only brokers"
  assert_contains "$main_tf" 'shared_kafka_topic_arn_prefix' "live-e2e derives kafka topic arn prefixes for IAM auth"
  assert_contains "$main_tf" 'replace(local.shared_kafka_cluster_arn, ":cluster/", ":topic/")' "live-e2e topic arn prefixes tolerate disabled shared services"
  assert_contains "$main_tf" 'shared_kafka_group_arn_prefix' "live-e2e derives kafka consumer group arn prefixes for IAM auth"
  assert_contains "$main_tf" 'replace(local.shared_kafka_cluster_arn, ":cluster/", ":group/")' "live-e2e group arn prefixes tolerate disabled shared services"
  assert_contains "$main_tf" 'resource "aws_iam_role" "proof_requestor_task"' "live-e2e provisions a proof-requestor task role"
  assert_contains "$main_tf" 'resource "aws_iam_role" "proof_funder_task"' "live-e2e provisions a proof-funder task role"
  assert_contains "$main_tf" 'resource "aws_iam_role_policy" "proof_requestor_task_access"' "live-e2e provisions proof-requestor kafka task access"
  assert_contains "$main_tf" 'resource "aws_iam_role_policy" "proof_funder_task_access"' "live-e2e provisions proof-funder kafka task access"
  assert_contains "$main_tf" '"kafka-cluster:Connect"' "live-e2e grants kafka connect permissions to proof task roles"
  assert_contains "$main_tf" 'resources = [local.shared_kafka_cluster_arn]' "live-e2e proof task roles re-use the guarded MSK cluster arn"

  assert_contains "$main_tf" '"/usr/local/bin/proof-requestor"' "live-e2e requestor still launches proof-requestor binary"
  assert_contains "$main_tf" '"--postgres-dsn"' "live-e2e requestor command includes postgres dsn"
  assert_contains "$main_tf" '"--owner"' "live-e2e requestor command includes owner"
  assert_contains "$main_tf" '"--sp1-requestor-address"' "live-e2e requestor command includes requestor address"
  assert_contains "$main_tf" '"--sp1-requestor-key-secret-arn"' "live-e2e requestor command includes requestor key reference"
  assert_contains "$main_tf" '"--chain-id"' "live-e2e requestor command includes chain id"
  assert_contains "$main_tf" '"--queue-brokers"' "live-e2e requestor command includes kafka brokers"
  assert_contains "$main_tf" 'local.shared_kafka_bootstrap_brokers,' "live-e2e proof tasks use IAM kafka brokers"
  assert_contains "$main_tf" '"--sp1-bin"' "live-e2e requestor command includes prover adapter binary"
  assert_contains "$main_tf" 'name      = "PROOF_REQUESTOR_KEY"' "live-e2e requestor task keeps requestor secret name"
  assert_contains "$main_tf" 'task_role_arn            = aws_iam_role.proof_requestor_task[0].arn' "live-e2e requestor task definition uses the proof-requestor task role"

  assert_contains "$main_tf" '"/usr/local/bin/proof-funder"' "live-e2e funder still launches proof-funder binary"
  assert_contains "$main_tf" '"--owner-id"' "live-e2e funder command includes owner id"
  assert_contains "$main_tf" '"--min-balance-wei"' "live-e2e funder command includes minimum balance threshold"
  assert_contains "$main_tf" '"--critical-balance-wei"' "live-e2e funder command includes critical balance threshold"
  assert_contains "$main_tf" 'name      = "PROOF_FUNDER_KEY"' "live-e2e funder task keeps funder secret name"
  assert_contains "$main_tf" 'valueFrom = local.shared_sp1_funder_secret_arn' "live-e2e funder task uses funder secret ARN"
  assert_contains "$main_tf" 'task_role_arn            = aws_iam_role.proof_funder_task[0].arn' "live-e2e funder task definition uses the proof-funder task role"
  assert_contains "$outputs_tf" 'output "shared_sp1_requestor_address"' "live-e2e exports the shared proof requestor address"
  assert_contains "$outputs_tf" 'trimspace(var.shared_sp1_requestor_address)' "live-e2e output keeps the rendered proof requestor address"
  assert_contains "$outputs_tf" 'output "shared_sp1_rpc_url"' "live-e2e exports the shared succinct rpc url"
  assert_contains "$outputs_tf" 'trimspace(var.shared_sp1_rpc_url)' "live-e2e output keeps the rendered succinct rpc url"

  assert_contains "$main_tf" 'name  = "SP1_NETWORK_RPC_URL"' "live-e2e proof task env includes SP1 rpc url"
  assert_contains "$main_tf" 'name  = "JUNO_QUEUE_KAFKA_AUTH_MODE"' "live-e2e proof task env includes kafka auth mode"
  assert_contains "$main_tf" 'value = "aws-msk-iam"' "live-e2e proof task env pins MSK IAM auth"
  assert_contains "$main_tf" 'name  = "JUNO_QUEUE_KAFKA_AWS_REGION"' "live-e2e proof task env includes kafka iam region"
  assert_contains "$main_tf" 'name  = "SP1_DEPOSIT_PROGRAM_URL"' "live-e2e proof task env includes deposit program url"
  assert_contains "$main_tf" 'name  = "SP1_WITHDRAW_PROGRAM_URL"' "live-e2e proof task env includes withdraw program url"
  assert_contains "$main_tf" 'name  = "SP1_DEPOSIT_PROGRAM_VKEY"' "live-e2e proof task env includes deposit vkey"
  assert_contains "$main_tf" 'name  = "SP1_WITHDRAW_PROGRAM_VKEY"' "live-e2e proof task env includes withdraw vkey"

  assert_contains "$variables_tf" 'Required when provision_shared_services is true' "live-e2e documents explicit proof image requirement"
  assert_contains "$main_tf" 'shared_proof_service_image must be set when provision_shared_services=true.' "live-e2e fails closed without explicit proof image"
  assert_contains "$main_tf" 'shared_proof_service_image         = trimspace(var.shared_proof_service_image)' "live-e2e uses explicit proof image input directly"
  assert_not_contains "$main_tf" 'repository_url}:latest' "live-e2e no longer defaults proof services to empty terraform-managed latest tag"
  assert_contains "$main_tf" '!local.shared_proof_runtime_enabled || local.shared_sp1_requestor_address != ""' "live-e2e gates active proof services behind runtime contract"
  assert_contains "$main_tf" 'shared_sp1_requestor_address must be set when shared_ecs_desired_count > 0' "live-e2e blocks active proof services without requestor address"
  assert_contains "$main_tf" 'private_subnets_by_az' "live-e2e derives shared subnets from private subnets only"
  assert_contains "$main_tf" 'if !s.map_public_ip_on_launch' "live-e2e filters public subnets out of shared subnet auto-selection"
  assert_contains "$main_tf" 'public_subnets_by_az' "live-e2e derives runner/operator subnets from public subnets"
  assert_contains "$main_tf" 'if s.map_public_ip_on_launch' "live-e2e filters private subnets out of runner/operator auto-selection"
  assert_contains "$main_tf" 'selected_subnet_id = var.subnet_id != "" ? var.subnet_id : local.public_one_per_az[0]' "live-e2e defaults runner/operator hosts onto a deterministic public subnet"
  assert_not_contains "$main_tf" 'selected_subnet_id = var.subnet_id != "" ? var.subnet_id : data.aws_subnets.selected_vpc.ids[0]' "live-e2e no longer chooses runner/operator subnets from an unordered vpc subnet list"
  assert_contains "$main_tf" 'description     = "Juno RPC from runner"' "live-e2e permits runner access to operator Juno RPC for backoffice MPC balance reads"
  assert_contains "$main_tf" 'from_port       = 18232' "live-e2e pins operator Juno RPC ingress to port 18232"
  assert_contains "$main_tf" 'to_port         = 18232' "live-e2e exposes only the operator Juno RPC port to the runner"
  assert_contains "$main_tf" 'check "shared_ecs_private_subnets_when_no_public_ip"' "live-e2e guards shared ECS subnet/public-ip compatibility"
  assert_contains "$main_tf" 'shared proof services require private shared_subnet_ids when shared_ecs_assign_public_ip=false.' "live-e2e fails closed on public shared subnets without public IPs"
  assert_contains "$main_tf" 'data "aws_route_table" "shared"' "live-e2e resolves route tables for shared subnets"
  assert_contains "$main_tf" 'resource "aws_security_group" "shared_vpc_endpoints"' "live-e2e provisions a dedicated security group for interface endpoints"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "secretsmanager"' "live-e2e provisions a Secrets Manager VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "ecr_api"' "live-e2e provisions an ECR API VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "ecr_dkr"' "live-e2e provisions an ECR DKR VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "sts"' "live-e2e provisions an STS VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "kms"' "live-e2e provisions a KMS VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "logs"' "live-e2e provisions a CloudWatch Logs VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "s3"' "live-e2e provisions an S3 gateway endpoint"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.secretsmanager"' "live-e2e points the Secrets Manager endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.ecr.api"' "live-e2e points the ECR API endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.ecr.dkr"' "live-e2e points the ECR DKR endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.sts"' "live-e2e points the STS endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.kms"' "live-e2e points the KMS endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.logs"' "live-e2e points the CloudWatch Logs endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name      = "com.amazonaws.${var.aws_region}.s3"' "live-e2e points the S3 endpoint at the deployment region"
  assert_contains "$main_tf" 'route_table_ids   = local.shared_route_table_ids' "live-e2e attaches the S3 gateway endpoint to the shared route tables"
  assert_contains "$main_tf" 'security_group_ids  = [aws_security_group.shared_vpc_endpoints[0].id]' "live-e2e constrains interface endpoints behind the dedicated SG"
  assert_contains "$main_tf" 'private_dns_enabled = true' "live-e2e enables private DNS on interface endpoints"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "shared_postgres_instance_cpu"' "live-e2e monitors Aurora CPU per instance"
  assert_contains "$monitoring_tf" 'var.provision_shared_services ? aws_rds_cluster_instance.shared : {}' "live-e2e derives Aurora CPU alarms from the keyed cluster instances"
  assert_not_contains "$monitoring_tf" 'aws_rds_cluster_instance.shared[0].identifier' "live-e2e no longer indexes keyed Aurora instances numerically"

  printf 'live_e2e package_a_snapshot_test: PASS\n'
}

main "$@"
