#!/usr/bin/env bash
# shellcheck shell=bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
source "$REPO_ROOT/deploy/production/tests/common_test.sh"

assert_not_contains() {
  local haystack="$1"
  local needle="$2"
  local msg="$3"
  if [[ "$haystack" == *"$needle"* ]]; then
    printf 'assert_not_contains failed: %s: found=%q\n' "$msg" "$needle" >&2
    exit 1
  fi
}

main() {
  local main_tf variables_tf monitoring_tf outputs_tf versions_tf password_block critical_hmac_random critical_hmac_secret critical_hmac_version key_rotation failover restore_runbook min_healthy_count max_healthy_count rollback_count proof_role_asg wireguard_role_asg proof_role_launch_template ipfs_launch_template wireguard_role_launch_template
  main_tf="$(cat "$SCRIPT_DIR/main.tf")"
  variables_tf="$(cat "$SCRIPT_DIR/variables.tf")"
  monitoring_tf="$(cat "$SCRIPT_DIR/monitoring.tf")"
  outputs_tf="$(cat "$SCRIPT_DIR/outputs.tf")"
  versions_tf="$(cat "$SCRIPT_DIR/versions.tf")"
  proof_role_asg="$(awk '
    /resource "aws_autoscaling_group" "proof_role" \{/ { in_block = 1 }
    in_block { print }
    in_block && /^\}/ { exit }
  ' "$SCRIPT_DIR/main.tf")"
  proof_role_launch_template="$(awk '
    /resource "aws_launch_template" "proof_role" \{/ { in_block = 1 }
    in_block { print }
    in_block && /^\}/ { exit }
  ' "$SCRIPT_DIR/main.tf")"
  ipfs_launch_template="$(awk '
    /resource "aws_launch_template" "ipfs" \{/ { in_block = 1 }
    in_block { print }
    in_block && /^\}/ { exit }
  ' "$SCRIPT_DIR/main.tf")"
  wireguard_role_asg="$(awk '
    /resource "aws_autoscaling_group" "wireguard_role" \{/ { in_block = 1 }
    in_block { print }
    in_block && /^\}/ { exit }
  ' "$SCRIPT_DIR/main.tf")"
  wireguard_role_launch_template="$(awk '
    /resource "aws_launch_template" "wireguard_role" \{/ { in_block = 1 }
    in_block { print }
    in_block && /^\}/ { exit }
  ' "$SCRIPT_DIR/main.tf")"
  password_block="$(awk '
    /variable "shared_postgres_password" \{/ { in_block = 1 }
    in_block { print }
    in_block && /^\}/ { exit }
  ' "$SCRIPT_DIR/variables.tf")"
  critical_hmac_random="$(awk '
    /resource "random_password" "shared_kafka_critical_hmac_key" \{/ { in_block = 1 }
    in_block { print }
    in_block && /^\}/ { exit }
  ' "$SCRIPT_DIR/main.tf")"
  critical_hmac_secret="$(awk '
    /resource "aws_secretsmanager_secret" "shared_kafka_critical_hmac_key" \{/ { in_block = 1 }
    in_block { print }
    in_block && /^\}/ { exit }
  ' "$SCRIPT_DIR/main.tf")"
  critical_hmac_version="$(awk '
    /resource "aws_secretsmanager_secret_version" "shared_kafka_critical_hmac_key" \{/ { in_block = 1 }
    in_block { print }
    in_block && /^\}/ { exit }
  ' "$SCRIPT_DIR/main.tf")"
  shared_ecs_desired_count_block="$(awk '
    /variable "shared_ecs_desired_count" \{/ { in_block = 1 }
    in_block { print }
    in_block && /^\}/ { exit }
  ' "$SCRIPT_DIR/variables.tf")"
  shared_proof_requestor_desired_count_block="$(awk '
    /variable "shared_proof_requestor_desired_count" \{/ { in_block = 1 }
    in_block { print }
    in_block && /^\}/ { exit }
  ' "$SCRIPT_DIR/variables.tf")"
  shared_proof_funder_desired_count_block="$(awk '
    /variable "shared_proof_funder_desired_count" \{/ { in_block = 1 }
    in_block { print }
    in_block && /^\}/ { exit }
  ' "$SCRIPT_DIR/variables.tf")"
  key_rotation="$(cat "$REPO_ROOT/deploy/shared/runbooks/proof-key-rotation.md")"
  failover="$(cat "$REPO_ROOT/deploy/shared/runbooks/proof-requestor-failover.md")"
  restore_runbook="$(cat "$REPO_ROOT/deploy/shared/runbooks/aurora-dr-restore.md")"

  assert_contains "$main_tf" 'check "distinct_proof_secret_arns"' "distinct proof secret ARN guard"
  assert_contains "$versions_tf" 'backend "s3" {}' "production-shared declares an s3 backend block for coordinator bootstrap"
  assert_contains "$main_tf" 'check "proof_service_image_ecr_scope"' "explicit ECR image repository scope guard"
  assert_contains "$main_tf" 'check "shared_ecs_private_subnets_when_no_public_ip"' "shared ecs subnet/public-ip compatibility guard"
  assert_contains "$main_tf" 'shared_proof_service_image_ecr_repository_arn must be set when shared_proof_service_image points at an explicit ECR repository.' "explicit ECR image scope message"
  assert_contains "$main_tf" 'shared proof services require private shared_subnet_ids when shared_ecs_assign_public_ip=false.' "production-shared fails closed on public shared subnets without public IPs"
  assert_contains "$main_tf" 'shared_kafka_cluster_arn                     = try(aws_msk_cluster.shared[0].arn, "")' "production-shared guards the optional shared kafka cluster arn when Terraform has not populated it yet"
  assert_contains "$main_tf" 'shared_kafka_topic_arn_prefix                = replace(local.shared_kafka_cluster_arn, ":cluster/", ":topic/")' "production-shared derives kafka topic arns from the guarded cluster arn"
  assert_contains "$main_tf" 'shared_kafka_group_arn_prefix                = replace(local.shared_kafka_cluster_arn, ":cluster/", ":group/")' "production-shared derives kafka group arns from the guarded cluster arn"

  assert_not_contains "$main_tf" 'AmazonECSTaskExecutionRolePolicy' "managed ECS execution policy removed"
  assert_contains "$main_tf" 'sid = "AllowECRAuthorizationToken"' "execution role keeps required ECR auth token call"
  assert_contains "$main_tf" 'sid = "AllowProofRequestorImagePull"' "requestor execution role scopes image pull"
  assert_contains "$main_tf" 'sid = "AllowProofFunderImagePull"' "funder execution role scopes image pull"
  assert_contains "$main_tf" 'resources = [local.shared_proof_service_ecr_repository_arn]' "ECR image pull scope uses configured repository ARN"
  assert_contains "$main_tf" 'sid = "AllowProofRequestorLogWrite"' "requestor log write scope present"
  assert_contains "$main_tf" 'sid = "AllowProofFunderLogWrite"' "funder log write scope present"
  assert_contains "$main_tf" 'trimsuffix(aws_cloudwatch_log_group.proof_requestor.arn, ":*")' "requestor log group scope is explicit"
  assert_contains "$main_tf" 'trimsuffix(aws_cloudwatch_log_group.proof_funder.arn, ":*")' "funder log group scope is explicit"
  assert_contains "$main_tf" 'resources = [var.shared_sp1_requestor_secret_arn]' "requestor secret scope uses only requestor ARN"
  assert_contains "$main_tf" 'resources = [var.shared_sp1_funder_secret_arn, var.shared_sp1_requestor_secret_arn]' "funder secret scope includes both proof secrets"
  assert_contains "$main_tf" 'resource "aws_secretsmanager_secret" "shared_postgres_dsn"' "production-shared provisions a dedicated postgres dsn secret"
  assert_contains "$main_tf" 'resources = [aws_secretsmanager_secret.shared_postgres_dsn.arn]' "execution roles can read only the shared postgres dsn secret"
  assert_contains "$main_tf" 'resource "aws_secretsmanager_secret" "shared_ipfs_api_bearer_token"' "production-shared provisions a dedicated IPFS API bearer token secret"
  assert_contains "$main_tf" 'resources = [aws_secretsmanager_secret.shared_ipfs_api_bearer_token.arn]' "production-shared constrains IPFS secret reads to the shared IPFS bearer token secret"
  assert_contains "$main_tf" 'resource "aws_security_group" "ipfs_lb"' "production-shared provisions a dedicated IPFS load balancer security group"
  assert_contains "$main_tf" 'load_balancer_type               = "application"' "production-shared uses an ALB for IPFS"
  assert_contains "$main_tf" 'protocol    = "HTTP"' "production-shared exposes the IPFS API over HTTP through the ALB"
  assert_contains "$main_tf" 'path     = "/healthz"' "production-shared configures an HTTP health check for the IPFS ALB"
  assert_contains "$main_tf" 'description     = "IPFS API from the internal load balancer"' "production-shared only allows IPFS instances to receive traffic from the IPFS ALB"
  assert_contains "$main_tf" 'location = /healthz' "production-shared nginx exposes an unauthenticated health endpoint for the IPFS ALB"
  assert_contains "$main_tf" 'resource "aws_secretsmanager_secret" "shared_kafka_critical_hmac_key"' "production-shared provisions a dedicated Kafka critical-topic HMAC secret"
  assert_not_contains "$critical_hmac_random" 'local.shared_queue_uses_kafka' "critical-topic HMAC random material is transport-neutral"
  assert_not_contains "$critical_hmac_secret" 'local.shared_queue_uses_kafka' "critical-topic HMAC secret is transport-neutral"
  assert_not_contains "$critical_hmac_version" 'local.shared_queue_uses_kafka' "critical-topic HMAC secret version is transport-neutral"
  assert_contains "$main_tf" 'resource "aws_security_group" "proof_role"' "production-shared provisions a dedicated proof-role security group"
  assert_contains "$main_tf" 'resource "aws_launch_template" "proof_role"' "production-shared provisions a proof-role launch template"
  assert_contains "$proof_role_launch_template" 'metadata_options {' "production-shared proof-role launch template configures instance metadata options"
  assert_contains "$proof_role_launch_template" 'http_tokens   = "required"' "production-shared proof-role launch template requires IMDSv2 tokens"
  assert_contains "$main_tf" 'resource "aws_autoscaling_group" "proof_role"' "production-shared provisions a proof-role autoscaling group"
  assert_contains "$main_tf" 'resource "aws_iam_instance_profile" "proof_role"' "production-shared provisions a proof-role instance profile"
  assert_contains "$main_tf" 'resource "aws_iam_role_policy_attachment" "proof_role_ssm_managed_instance_core"' "production-shared attaches SSM managed instance core to the proof-role instance role"
  assert_contains "$main_tf" 'policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"' "production-shared uses the AWS-managed SSM instance core policy for proof-role canaries"
  assert_contains "$proof_role_launch_template" 'snap list amazon-ssm-agent' "production-shared proof-role bootstrap prefers the preinstalled snap SSM agent when present"
  assert_contains "$proof_role_launch_template" 'snap.amazon-ssm-agent.amazon-ssm-agent.service' "production-shared proof-role bootstrap enables and starts the snap SSM agent service"
  assert_contains "$proof_role_launch_template" 'debian_amd64' "production-shared proof-role bootstrap supports amd64 SSM agent packages"
  assert_contains "$proof_role_launch_template" 'debian_arm64' "production-shared proof-role bootstrap supports arm64 SSM agent packages"
  assert_contains "$proof_role_launch_template" 'amazon-ssm-${var.aws_region}' "production-shared proof-role bootstrap downloads regional SSM agent fallback packages"
  assert_contains "$proof_role_launch_template" 'run_with_retry dpkg -i "$ssm_agent_deb"' "production-shared proof-role bootstrap retries SSM agent package installation"
  assert_contains "$proof_role_asg" 'aws_iam_role_policy_attachment.proof_role_ssm_managed_instance_core' "production-shared proof-role ASG waits for the SSM managed instance policy attachment"
  assert_contains "$main_tf" 'proof-requestor.service' "production-shared writes a proof-requestor systemd unit for the proof role"
  assert_contains "$main_tf" 'proof-funder.service' "production-shared writes a proof-funder systemd unit for the proof role"
  assert_contains "$main_tf" 'var.shared_proof_role_min_size == 0 || var.shared_proof_role_desired_capacity >= var.shared_proof_role_min_size' "production-shared validates proof-role desired capacity against min size"
  assert_contains "$main_tf" 'var.shared_proof_role_max_size >= var.shared_proof_role_desired_capacity' "production-shared validates proof-role max size against desired capacity"
  assert_contains "$main_tf" 'secretsmanager get-secret-value --secret-id "$requestor_secret_arn"' "production-shared proof-role bootstrap reads the requestor signer secret at runtime"
  assert_contains "$main_tf" 'secretsmanager get-secret-value --secret-id "$funder_secret_arn"' "production-shared proof-role bootstrap reads the funder signer secret at runtime"
  assert_contains "$main_tf" 'resource "aws_security_group" "wireguard_role"' "production-shared provisions a wireguard role security group"
  assert_contains "$main_tf" 'resource "aws_launch_template" "wireguard_role"' "production-shared provisions a wireguard role launch template"
  assert_contains "$wireguard_role_launch_template" 'metadata_options {' "production-shared wireguard-role launch template configures instance metadata options"
  assert_contains "$wireguard_role_launch_template" 'http_tokens   = "required"' "production-shared wireguard-role launch template requires IMDSv2 tokens"
  assert_contains "$main_tf" 'resource "aws_autoscaling_group" "wireguard_role"' "production-shared provisions a wireguard role autoscaling group"
  assert_contains "$main_tf" 'resource "aws_lb" "wireguard"' "production-shared provisions a UDP network load balancer for wireguard"
  assert_contains "$main_tf" 'resource "aws_lb_target_group" "wireguard_udp"' "production-shared provisions a wireguard UDP target group"
  assert_contains "$main_tf" 'resource "aws_lb_listener" "wireguard_udp"' "production-shared provisions a wireguard UDP listener"
  assert_contains "$main_tf" 'resource "aws_secretsmanager_secret" "shared_wireguard_server_key"' "production-shared provisions a dedicated wireguard server-key secret"
  assert_contains "$main_tf" 'resource "random_id" "shared_wireguard_server_key_material"' "production-shared generates durable wireguard server-key material"
  assert_contains "$main_tf" 'resource "aws_secretsmanager_secret_version" "shared_wireguard_server_key"' "production-shared seeds the shared wireguard server-key secret value"
  assert_contains "$main_tf" 'resource "aws_secretsmanager_secret" "shared_wireguard_peer_config"' "production-shared provisions per-peer wireguard config secrets"
  assert_contains "$main_tf" 'wireguard_legacy_enabled       = local.wireguard_enabled && length(var.shared_wireguard_public_subnet_ids) == 0' "production-shared disables the legacy singleton wireguard path when role subnets are supplied"
  assert_contains "$main_tf" 'resource "aws_instance" "wireguard_gateway"' "production-shared keeps the legacy wireguard gateway resource behind an explicit compatibility gate"
  assert_contains "$main_tf" 'count                       = local.wireguard_legacy_enabled ? 1 : 0' "production-shared gates the legacy wireguard instance behind the compatibility flag"
  assert_contains "$ipfs_launch_template" 'metadata_options {' "production-shared ipfs launch template configures instance metadata options"
  assert_contains "$ipfs_launch_template" 'http_tokens   = "required"' "production-shared ipfs launch template requires IMDSv2 tokens"
  assert_contains "$main_tf" 'for_each = local.shared_wireguard_named_peers' "production-shared materializes named wireguard peers"
  assert_contains "$main_tf" 'load_balancer_type               = "network"' "production-shared uses an NLB for wireguard"
  assert_contains "$main_tf" 'protocol    = "UDP"' "production-shared exposes wireguard over UDP"
  assert_contains "$main_tf" 'aws --region ${var.aws_region} secretsmanager get-secret-value --secret-id "$wireguard_server_key_secret_arn"' "production-shared wireguard bootstrap hydrates the shared server key from Secrets Manager"
  assert_contains "$main_tf" 'address=/${var.shared_wireguard_backoffice_hostname}/$${endpoint_ip}' "production-shared maps the backoffice hostname to each internal endpoint IP over wireguard"
  assert_contains "$variables_tf" 'variable "shared_sp1_requestor_address"' "production-shared exposes shared proof requestor address input"
  assert_contains "$variables_tf" 'variable "shared_ipfs_data_volume_size_gb"' "production-shared exposes dedicated IPFS data volume sizing"
  assert_contains "$variables_tf" 'variable "shared_wireguard_public_subnet_id"' "production-shared exposes the dedicated wireguard public subnet input"
  assert_contains "$variables_tf" 'variable "shared_wireguard_public_subnet_ids"' "production-shared exposes the active-active wireguard public subnet inputs"
  assert_contains "$variables_tf" 'variable "shared_wireguard_source_cidrs"' "production-shared exposes wireguard source cidrs for handoff and backoffice allowlisting"
  assert_contains "$variables_tf" 'variable "shared_wireguard_role_ami_id"' "production-shared exposes the wireguard role ami input"
  assert_contains "$variables_tf" 'variable "shared_wireguard_named_peers"' "production-shared exposes named wireguard peers"
  assert_contains "$variables_tf" 'variable "shared_wireguard_backoffice_private_endpoint_ips"' "production-shared exposes backoffice private endpoint IPs for wireguard peers"
  assert_contains "$variables_tf" 'variable "shared_proof_role_min_size"' "production-shared exposes proof-role min size"
  assert_contains "$variables_tf" 'variable "shared_proof_role_desired_capacity"' "production-shared exposes proof-role desired capacity"
  assert_contains "$variables_tf" 'variable "shared_proof_role_max_size"' "production-shared exposes proof-role max size"
  assert_contains "$variables_tf" 'variable "shared_proof_role_instance_type"' "production-shared exposes proof-role instance type"
  assert_contains "$variables_tf" 'variable "shared_proof_role_ami_id"' "production-shared exposes proof-role AMI input"
  assert_contains "$variables_tf" 'variable "shared_wireguard_backoffice_private_endpoint"' "production-shared exposes the private backoffice endpoint input"
  assert_contains "$variables_tf" 'variable "shared_wireguard_backoffice_hostname"' "production-shared exposes the vpn backoffice hostname input"
  assert_contains "$variables_tf" 'variable "shared_service_client_security_group_ids"' "production-shared exposes shared client security groups for postgres and msk ingress"
  assert_contains "$variables_tf" 'variable "shared_ipfs_client_security_group_ids"' "production-shared exposes shared client security groups for ipfs ingress"
  assert_contains "$variables_tf" 'alarm_actions must include at least one CloudWatch action ARN.' "production-shared requires alarm actions"
  assert_contains "$outputs_tf" 'output "shared_sp1_requestor_address"' "production-shared exports shared proof requestor address"
  assert_contains "$outputs_tf" 'output "shared_sp1_rpc_url"' "production-shared exports shared sp1 rpc url"
  assert_contains "$outputs_tf" 'output "shared_ipfs_nlb_dns"' "production-shared keeps the legacy shared IPFS dns output name stable"
  assert_contains "$outputs_tf" 'output "shared_ipfs_api_url"' "production-shared exports the shared IPFS api url"
  assert_contains "$outputs_tf" 'output "shared_ipfs_api_auth_secret_arn"' "production-shared exports the shared IPFS bearer token secret ARN"
  assert_contains "$outputs_tf" 'output "shared_queue_driver"' "production-shared exports the selected shared queue transport"
  assert_contains "$outputs_tf" 'output "shared_proof_queue_driver"' "production-shared exports the selected proof queue transport"
  assert_contains "$outputs_tf" 'value       = local.shared_queue_uses_kafka ? var.shared_kafka_port : null' "production-shared leaves the Kafka port output empty when the shared queue uses Postgres"
  assert_contains "$outputs_tf" 'output "shared_kafka_critical_hmac_secret_arn"' "production-shared exports the Kafka critical-topic HMAC secret ARN"
  assert_contains "$outputs_tf" 'output "shared_proof_role_asg_name"' "production-shared exports the proof-role autoscaling group name"
  assert_contains "$outputs_tf" 'output "shared_proof_role_launch_template_id"' "production-shared exports the proof-role launch template id"
  assert_contains "$outputs_tf" 'output "shared_proof_role"' "production-shared exports the structured proof-role contract"
  assert_contains "$outputs_tf" 'output "shared_wireguard_role_asg_name"' "production-shared exports the wireguard-role autoscaling group name"
  assert_contains "$outputs_tf" 'output "shared_wireguard_role_launch_template_id"' "production-shared exports the wireguard-role launch template id"
  assert_contains "$outputs_tf" 'output "shared_wireguard_role"' "production-shared exports the structured wireguard-role contract"
  assert_contains "$outputs_tf" 'source_cidrs                    = var.shared_wireguard_source_cidrs' "production-shared exports wireguard source cidrs in the structured role contract"
  assert_contains "$outputs_tf" 'peer_roster_secret_arns         = []' "production-shared keeps the disabled wireguard-role output shape stable"
  assert_contains "$outputs_tf" 'peer_config_secret_arns         = {}' "production-shared keeps disabled wireguard peer config outputs typed"
  assert_contains "$outputs_tf" 'output "shared_wireguard_nlb_dns_name"' "production-shared exports the wireguard nlb dns name"
  assert_contains "$outputs_tf" 'output "shared_wireguard_server_key_secret_arn"' "production-shared exports the wireguard server-key secret arn"
  assert_contains "$outputs_tf" 'output "shared_wireguard_peer_config_secret_arns"' "production-shared exports the named wireguard peer config secret arns"
  assert_contains "$outputs_tf" 'output "shared_wireguard_backoffice_private_endpoint_ips"' "production-shared exports the backoffice private endpoint IP set"
  assert_contains "$variables_tf" 'At least two private subnet IDs in distinct AZs for Aurora, MSK, ECS, and the IPFS load balancer.' "production-shared documents private shared subnet requirement"
  assert_contains "$variables_tf" $'variable "shared_msk_broker_instance_type" {\n  description = "MSK broker instance type."\n  type        = string\n  default     = "kafka.m5.large"' "production-shared defaults MSK to an IAM-ready broker class"
  assert_contains "$variables_tf" 'variable "shared_queue_driver"' "production-shared exposes queue transport selection"
  assert_contains "$variables_tf" 'shared_queue_driver must be one of kafka or postgres.' "production-shared validates queue transport values"
  assert_contains "$variables_tf" 'variable "shared_proof_queue_driver"' "production-shared exposes proof queue transport override"
  assert_contains "$variables_tf" 'shared_proof_queue_driver must be empty or one of kafka or postgres.' "production-shared validates proof queue transport override values"
  assert_contains "$variables_tf" 'variable "shared_base_chain_id"' "production-shared exposes base chain id input"
  assert_contains "$variables_tf" 'variable "shared_deposit_image_id"' "production-shared exposes deposit image id input"
  assert_contains "$variables_tf" 'variable "shared_withdraw_image_id"' "production-shared exposes withdraw image id input"
  assert_contains "$variables_tf" 'variable "shared_sp1_deposit_program_url_override"' "production-shared exposes an explicit deposit program url override"
  assert_contains "$variables_tf" 'variable "shared_sp1_withdraw_program_url_override"' "production-shared exposes an explicit withdraw program url override"
  assert_contains "$main_tf" 'local.shared_proof_requestor_command' "production-shared requestor task uses generated command"
  assert_contains "$main_tf" '"--sp1-requestor-address", local.shared_sp1_requestor_address' "production-shared requestor command includes requestor address"
  assert_contains "$main_tf" '"--chain-id", tostring(var.shared_base_chain_id)' "production-shared requestor command includes chain id"
  assert_contains "$main_tf" '"--postgres-dsn-env", "POSTGRES_DSN"' "production-shared requestor command resolves DSN from secret-backed env"
  assert_not_contains "$main_tf" '"--postgres-dsn", local.shared_postgres_dsn' "production-shared does not expose Postgres DSN in ECS command lines"
  assert_contains "$main_tf" '"--queue-brokers", local.shared_kafka_bootstrap_brokers' "production-shared proof tasks use IAM kafka brokers"
  assert_contains "$main_tf" 'shared_queue_driver                          = lower(trimspace(var.shared_queue_driver))' "production-shared normalizes the shared proof queue driver"
  assert_contains "$main_tf" 'shared_proof_queue_driver                    = trimspace(var.shared_proof_queue_driver) == "" ? local.shared_queue_driver : lower(trimspace(var.shared_proof_queue_driver))' "production-shared lets proof ECS cut over before MSK deletion"
  assert_contains "$main_tf" 'shared_proof_queue_uses_kafka                = local.shared_proof_queue_driver == "kafka"' "production-shared tracks proof kafka usage separately from MSK lifecycle"
  assert_contains "$main_tf" 'shared_queue_postgres_args                   = ["--queue-postgres-dsn-env", "POSTGRES_DSN"]' "production-shared can pass queue postgres DSN through secret-backed env"
  assert_contains "$main_tf" 'local.shared_proof_queue_driver == "postgres" ? local.shared_queue_postgres_args : local.shared_queue_kafka_args' "production-shared proof commands switch queue args by proof transport"
  assert_contains "$main_tf" 'count  = local.shared_proof_queue_uses_kafka ? 1 : 0' "production-shared only attaches proof task kafka IAM when proof tasks use kafka"
  assert_contains "$main_tf" 'shared_proof_queue_driver cannot be kafka when shared_queue_driver is postgres because MSK would be absent.' "production-shared rejects kafka proof queue without MSK"
  assert_contains "$main_tf" $'for_each = local.shared_queue_uses_kafka ? [1] : []\n    content {\n      sid = "AllowProofRoleKafkaAccess"' "production-shared keeps proof-role kafka IAM until MSK lifecycle ends"
  assert_contains "$main_tf" '--queue-driver ${local.shared_proof_queue_driver}' "production-shared proof-role systemd units use the proof queue driver"
  assert_contains "$main_tf" '${local.shared_proof_queue_driver == "postgres" ? "--queue-postgres-dsn-env POSTGRES_DSN" : "--queue-brokers ${local.shared_kafka_bootstrap_brokers}"}' "production-shared proof-role systemd units switch queue args by proof transport"
  assert_contains "$main_tf" 'local.shared_proof_funder_command' "production-shared funder task uses generated command"
  assert_contains "$main_tf" 'name      = "POSTGRES_DSN"' "production-shared injects Postgres DSN as an ECS secret"
  assert_contains "$main_tf" 'valueFrom = aws_secretsmanager_secret.shared_postgres_dsn.arn' "production-shared ECS DSN secret comes from dedicated secret ARN"
  assert_contains "$main_tf" '"--min-balance-wei", tostring(local.shared_sp1_required_credit_buffer)' "production-shared funder command includes min balance"
  assert_contains "$main_tf" '"--critical-balance-wei", tostring(local.shared_sp1_projected_with_overhead)' "production-shared funder command includes critical balance"
  assert_contains "$main_tf" 'name      = "PROOF_REQUESTOR_KEY"' "production-shared funder task also injects the requestor secret"
  assert_contains "$main_tf" 'resources = [var.shared_sp1_funder_secret_arn, var.shared_sp1_requestor_secret_arn]' "production-shared funder execution role can read both proof secrets"
  assert_contains "$main_tf" 'name  = "JUNO_QUEUE_KAFKA_AUTH_MODE"' "production-shared proof task env includes kafka auth mode"
  assert_contains "$main_tf" 'value = "aws-msk-iam"' "production-shared proof task env enforces aws-msk-iam"
  assert_contains "$main_tf" 'name  = "JUNO_QUEUE_KAFKA_AWS_REGION"' "production-shared proof task env includes kafka aws region"
  assert_contains "$main_tf" 'value = var.aws_region' "production-shared proof task env propagates aws region"
  assert_not_contains "$main_tf" 'connectivity_info {' "production-shared keeps MSK on the default same-VPC broker path"
  assert_not_contains "$main_tf" 'vpc_connectivity {' "production-shared does not enable MSK multi-VPC connectivity for same-VPC clients"
  assert_contains "$main_tf" 'name  = "SP1_NETWORK_RPC_URL"' "production-shared proof task env includes SP1 rpc url"
  assert_contains "$main_tf" 'name  = "SP1_REQUEST_CIRCUIT_VERSION"' "production-shared proof task env injects the compat SP1 request circuit version override"
  assert_contains "$main_tf" 'value = "v6.1.0"' "production-shared proof task env pins the compat SP1 request circuit version"
  assert_contains "$main_tf" 'name  = "SP1_DEPOSIT_PROGRAM_URL"' "production-shared proof task env includes deposit program url"
  assert_contains "$main_tf" 'name  = "SP1_WITHDRAW_PROGRAM_URL"' "production-shared proof task env includes withdraw program url"
  assert_contains "$main_tf" 'trimspace(var.shared_sp1_deposit_program_url_override) != "" ? trimspace(var.shared_sp1_deposit_program_url_override)' "production-shared prefers the explicit deposit program url override when provided"
  assert_contains "$main_tf" 'trimspace(var.shared_sp1_withdraw_program_url_override) != "" ? trimspace(var.shared_sp1_withdraw_program_url_override)' "production-shared prefers the explicit withdraw program url override when provided"
  assert_contains "$main_tf" 'shared_proof_requestor_desired_count         = coalesce(var.shared_proof_requestor_desired_count, var.shared_ecs_desired_count)' "production-shared allows proof-requestor desired count override"
  assert_contains "$main_tf" 'shared_proof_funder_desired_count            = coalesce(var.shared_proof_funder_desired_count, var.shared_ecs_desired_count)' "production-shared allows proof-funder desired count override"
  assert_contains "$variables_tf" 'variable "shared_proof_requestor_task_cpu"' "production-shared exposes proof-requestor task cpu override"
  assert_contains "$variables_tf" 'variable "shared_proof_requestor_task_memory"' "production-shared exposes proof-requestor task memory override"
  assert_contains "$variables_tf" 'variable "shared_proof_funder_task_cpu"' "production-shared exposes proof-funder task cpu override"
  assert_contains "$variables_tf" 'variable "shared_proof_funder_task_memory"' "production-shared exposes proof-funder task memory override"
  assert_contains "$variables_tf" 'shared_proof_requestor_task_cpu must be > 0 when set.' "production-shared validates proof-requestor task cpu override"
  assert_contains "$variables_tf" 'shared_proof_requestor_task_memory must be > 0 when set.' "production-shared validates proof-requestor task memory override"
  assert_contains "$variables_tf" 'shared_proof_funder_task_cpu must be > 0 when set.' "production-shared validates proof-funder task cpu override"
  assert_contains "$variables_tf" 'shared_proof_funder_task_memory must be > 0 when set.' "production-shared validates proof-funder task memory override"
  assert_contains "$main_tf" 'shared_proof_requestor_task_cpu              = coalesce(var.shared_proof_requestor_task_cpu, var.shared_ecs_task_cpu)' "production-shared defaults proof-requestor task cpu to shared task cpu"
  assert_contains "$main_tf" 'shared_proof_requestor_task_memory           = coalesce(var.shared_proof_requestor_task_memory, var.shared_ecs_task_memory)' "production-shared defaults proof-requestor task memory to shared task memory"
  assert_contains "$main_tf" 'shared_proof_funder_task_cpu                 = coalesce(var.shared_proof_funder_task_cpu, var.shared_ecs_task_cpu)' "production-shared defaults proof-funder task cpu to shared task cpu"
  assert_contains "$main_tf" 'shared_proof_funder_task_memory              = coalesce(var.shared_proof_funder_task_memory, var.shared_ecs_task_memory)' "production-shared defaults proof-funder task memory to shared task memory"
  assert_contains "$main_tf" 'cpu                      = tostring(local.shared_proof_requestor_task_cpu)' "production-shared sizes proof-requestor task from requestor-specific local"
  assert_contains "$main_tf" 'memory                   = tostring(local.shared_proof_requestor_task_memory)' "production-shared sizes proof-requestor memory from requestor-specific local"
  assert_contains "$main_tf" 'cpu                      = tostring(local.shared_proof_funder_task_cpu)' "production-shared sizes proof-funder task from funder-specific local"
  assert_contains "$main_tf" 'memory                   = tostring(local.shared_proof_funder_task_memory)' "production-shared sizes proof-funder memory from funder-specific local"
  assert_contains "$main_tf" 'desired_count   = local.shared_proof_requestor_desired_count' "production-shared scales proof-requestor independently"
  assert_contains "$main_tf" 'desired_count   = local.shared_proof_funder_desired_count' "production-shared scales proof-funder independently"
  assert_contains "$main_tf" 'shared_sp1_requestor_address must be set when a shared proof service desired count is > 0' "production-shared blocks active proof services without requestor address"
  assert_contains "$main_tf" 'task_role_arn            = aws_iam_role.proof_requestor_task.arn' "requestor task definition uses dedicated runtime role"
  assert_contains "$main_tf" 'task_role_arn            = aws_iam_role.proof_funder_task.arn' "funder task definition uses dedicated runtime role"
  assert_contains "$main_tf" 'sid = "AllowMSKConnect"' "proof runtime task roles can connect to MSK"
  assert_contains "$main_tf" 'sid = "AllowMSKTopicAccess"' "requestor task role grants broad kafka topic access"
  assert_contains "$main_tf" 'sid = "AllowMSKGroupAccess"' "requestor task role grants broad kafka group access"
  assert_contains "$main_tf" '"kafka-cluster:DescribeTopicDynamicConfiguration"' "requestor task role can inspect kafka topic configuration"
  assert_contains "$main_tf" '"kafka-cluster:WriteDataIdempotently"' "requestor task role supports idempotent kafka writes"
  assert_contains "$main_tf" 'resources = ["${local.shared_kafka_topic_arn_prefix}/*"]' "requestor task role scopes topic access to the shared cluster"
  assert_contains "$main_tf" 'resources = ["${local.shared_kafka_group_arn_prefix}/*"]' "requestor task role scopes group access to the shared cluster"
  assert_contains "$main_tf" 'sid = "AllowReadProofRequestsTopic"' "requestor task role can read proof request topic"
  assert_contains "$main_tf" 'sid = "AllowWriteProofResultsTopic"' "requestor task role can write fulfillment topic"
  assert_contains "$main_tf" 'sid = "AllowWriteProofFailuresTopic"' "requestor task role can write failure topic"
  assert_contains "$main_tf" 'sid = "AllowReadProofRequestorGroup"' "requestor task role can use its consumer group"
  assert_contains "$main_tf" 'sid = "AllowWriteOpsAlertsTopic"' "funder task role can emit ops alerts"

  assert_contains "$main_tf" 'description = "MSK broker mesh"' "MSK self-ingress rule exists"
  assert_contains "$main_tf" 'protocol    = "tcp"' "MSK self-ingress stays on TCP"
  assert_contains "$main_tf" 'from_port   = 9092' "MSK self-ingress lower port bound"
  assert_contains "$main_tf" 'to_port     = 9094' "MSK self-ingress upper port bound"
  assert_contains "$main_tf" 'min.insync.replicas = 2' "MSK durability policy"

  assert_contains "$main_tf" 'skip_final_snapshot       = false' "Aurora final snapshot required"
  assert_contains "$main_tf" 'final_snapshot_identifier = local.aurora_final_snapshot_identifier' "Aurora final snapshot identifier wired"
  assert_contains "$main_tf" 'deletion_protection       = true' "Aurora deletion protection enabled"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "shared_postgres_instance_cpu"' "production-shared monitors Aurora CPU per instance"
  assert_contains "$monitoring_tf" 'for_each            = aws_rds_cluster_instance.shared' "production-shared derives Aurora CPU alarms from keyed cluster instances"
  assert_not_contains "$monitoring_tf" 'aws_rds_cluster_instance.shared[0].identifier' "production-shared no longer indexes keyed Aurora instances numerically"

  assert_contains "$main_tf" 'desired_capacity          = var.shared_proof_role_desired_capacity' "production-shared drives proof-role capacity from explicit ASG inputs"
  assert_contains "$main_tf" 'min_size                  = var.shared_proof_role_min_size' "production-shared exposes proof-role minimum size on the ASG"
  assert_contains "$main_tf" 'max_size                  = var.shared_proof_role_max_size' "production-shared exposes proof-role maximum size on the ASG"
  assert_contains "$proof_role_asg" 'instance_refresh {' "production-shared refreshes proof-role instances on launch template changes"
  assert_contains "$proof_role_asg" 'strategy = "Rolling"' "production-shared uses rolling refresh for proof-role instances"
  assert_contains "$proof_role_asg" 'triggers = ["launch_template"]' "production-shared ties proof-role refresh to launch template changes"
  assert_contains "$main_tf" 'desired_capacity          = var.shared_wireguard_desired_capacity' "production-shared drives wireguard-role capacity from explicit ASG inputs"
  assert_contains "$main_tf" 'min_size                  = var.shared_wireguard_min_size' "production-shared exposes wireguard-role minimum size on the ASG"
  assert_contains "$main_tf" 'max_size                  = var.shared_wireguard_max_size' "production-shared exposes wireguard-role maximum size on the ASG"
  assert_contains "$main_tf" 'image_id               = trimspace(var.shared_wireguard_role_ami_id) != "" ? trimspace(var.shared_wireguard_role_ami_id) : data.aws_ami.ubuntu.id' "production-shared prefers a pinned wireguard role ami when provided"
  assert_contains "$wireguard_role_asg" 'instance_refresh {' "production-shared refreshes wireguard-role instances on launch template changes"
  assert_contains "$wireguard_role_asg" 'strategy = "Rolling"' "production-shared uses rolling refresh for wireguard-role instances"
  assert_contains "$wireguard_role_asg" 'triggers = ["launch_template"]' "production-shared ties wireguard-role refresh to launch template changes"

  assert_contains "$main_tf" 'health_check_type         = "ELB"' "IPFS ASG uses ELB health"
  assert_contains "$main_tf" 'shared_ipfs_min_size must be at least 2 to avoid a single-node IPFS deployment.' "IPFS redundancy precondition"
  assert_contains "$main_tf" 'volume_size           = var.shared_ipfs_data_volume_size_gb' "production-shared provisions a dedicated IPFS data volume"
  assert_contains "$main_tf" 'delete_on_termination = false' "production-shared preserves the dedicated IPFS data volume across instance replacement"
  assert_contains "$main_tf" '/var/lib/intents-juno/ipfs' "production-shared mounts a dedicated IPFS data path"
  assert_contains "$main_tf" 'enable_cross_zone_load_balancing = true' "production-shared enables cross-zone load balancing on the IPFS NLB"
  assert_not_contains "$main_tf" 'apt-get install -y awscli' "production-shared no longer depends on the missing Ubuntu awscli package for IPFS bootstrap"
  assert_contains "$main_tf" 'retry_apt() {' "production-shared retries IPFS bootstrap apt commands"
  assert_contains "$main_tf" 'rm -rf /var/lib/apt/lists/*' "production-shared clears stale apt indexes before retrying IPFS bootstrap"
  assert_contains "$main_tf" 'retry_apt apt-get update -y' "production-shared retries apt update during IPFS bootstrap"
  assert_contains "$main_tf" 'retry_apt apt-get install -y ca-certificates curl docker.io nginx unzip' "production-shared retries apt install during IPFS bootstrap"
  assert_contains "$main_tf" 'arch="$(uname -m)"' "production-shared detects the IPFS instance architecture before installing AWS CLI"
  assert_contains "$main_tf" 'awscli-exe-linux-$${awscli_arch}.zip' "production-shared installs AWS CLI from the official architecture-specific bundle"
  assert_contains "$main_tf" '/tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update' "production-shared installs AWS CLI v2 into a stable location"
  assert_contains "$main_tf" 'secretsmanager get-secret-value --secret-id "$ipfs_api_secret_arn"' "production-shared bootstraps the IPFS bearer token from Secrets Manager"
  assert_contains "$main_tf" 'proxy_pass http://127.0.0.1:5001;' "production-shared proxies authenticated IPFS API traffic to loopback Kubo"
  assert_contains "$main_tf" 'daemon --migrate=true --api /ip4/127.0.0.1/tcp/5001 --routing=dhtclient' "production-shared binds raw Kubo API to loopback only"
  assert_not_contains "$main_tf" '--api /ip4/0.0.0.0/tcp/5001' "production-shared no longer exposes raw Kubo on all interfaces"
  assert_contains "$main_tf" 'data "aws_route_table" "shared"' "production-shared resolves route tables for shared subnets"
  assert_contains "$main_tf" 'resource "aws_security_group" "shared_vpc_endpoints"' "production-shared provisions a dedicated security group for interface endpoints"
  assert_contains "$main_tf" 'description     = "Postgres from shared-service client security groups"' "production-shared allows postgres from explicit client security groups"
  assert_contains "$main_tf" 'description     = "MSK IAM bootstrap from shared-service client security groups"' "production-shared allows kafka from explicit client security groups"
  assert_contains "$main_tf" 'description     = "IPFS API from approved client security groups"' "production-shared allows ipfs from explicit client security groups"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "secretsmanager"' "production-shared provisions a Secrets Manager VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "ecr_api"' "production-shared provisions an ECR API VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "ecr_dkr"' "production-shared provisions an ECR DKR VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "sts"' "production-shared provisions an STS VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "kms"' "production-shared provisions a KMS VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "logs"' "production-shared provisions a CloudWatch Logs VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "s3"' "production-shared provisions an S3 gateway endpoint"
  assert_contains "$main_tf" 'description = "HTTPS from the VPC"' "production-shared opens interface endpoints to the whole VPC"
  assert_contains "$main_tf" 'cidr_blocks = [data.aws_vpc.selected.cidr_block]' "production-shared interface endpoints allow non-shared subnets"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.secretsmanager"' "production-shared points the Secrets Manager endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.ecr.api"' "production-shared points the ECR API endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.ecr.dkr"' "production-shared points the ECR DKR endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.sts"' "production-shared points the STS endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.kms"' "production-shared points the KMS endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.logs"' "production-shared points the CloudWatch Logs endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name      = "com.amazonaws.${var.aws_region}.s3"' "production-shared points the S3 endpoint at the deployment region"
  assert_contains "$main_tf" 'route_table_ids   = local.shared_route_table_ids' "production-shared attaches the S3 gateway endpoint to the shared route tables"
  assert_contains "$main_tf" 'security_group_ids  = [aws_security_group.shared_vpc_endpoints.id]' "production-shared constrains interface endpoints behind the dedicated SG"
  assert_contains "$main_tf" 'private_dns_enabled = true' "production-shared enables private DNS on interface endpoints"
  assert_contains "$main_tf" 'alias  = "dr"' "production-shared configures an aws dr provider alias"
  assert_contains "$variables_tf" 'variable "shared_postgres_dr_region"' "production-shared exposes the Aurora DR backup region"
  assert_not_contains "$variables_tf" 'trimspace(var.shared_postgres_dr_region) != trimspace(var.aws_region)' "production-shared no longer uses cross-variable validation in shared_postgres_dr_region"
  assert_contains "$main_tf" 'resource "aws_backup_vault" "shared_postgres"' "production-shared provisions a primary backup vault"
  assert_contains "$main_tf" 'resource "aws_backup_vault" "shared_postgres_dr"' "production-shared provisions a DR backup vault"
  assert_contains "$main_tf" 'provider = aws.dr' "production-shared binds DR backup resources to the dr provider"
  assert_contains "$main_tf" 'resource "aws_backup_plan" "shared_postgres"' "production-shared provisions an Aurora backup plan"
  assert_contains "$main_tf" 'copy_action {' "production-shared copies backups into the DR vault"
  assert_contains "$main_tf" 'destination_vault_arn = aws_backup_vault.shared_postgres_dr.arn' "production-shared targets the DR backup vault"
  assert_contains "$main_tf" 'resource "aws_backup_selection" "shared_postgres"' "production-shared selects the Aurora cluster for AWS Backup"
  assert_contains "$main_tf" 'resources    = [aws_rds_cluster.shared.arn]' "production-shared backs up the Aurora cluster ARN"
  assert_contains "$main_tf" 'resource "aws_iam_role" "shared_backup"' "production-shared provisions a dedicated AWS Backup role"
  assert_contains "$main_tf" 'AWSBackupServiceRolePolicyForBackup' "production-shared attaches the AWS Backup backup policy"
  assert_contains "$main_tf" 'AWSBackupServiceRolePolicyForRestores' "production-shared attaches the AWS Backup restore policy"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "withdrawal_dlq_depth"' "production-shared alarms on withdrawal dlq depth"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "confirmed_unmarked_count"' "production-shared alarms on confirmed-unmarked withdrawals"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "mark_paid_circuit_open"' "production-shared alarms on the withdraw mark-paid circuit breaker"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "deposit_proof_requested_count"' "production-shared alarms on stuck deposit proof requests"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "deposit_submitted_count"' "production-shared alarms on stuck submitted deposits"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "min_withdrawal_time_to_expiry_seconds"' "production-shared alarms on withdrawal expiry runway"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "checkpoint_pin_backlog"' "production-shared alarms on checkpoint pin backlog"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "tss_session_saturation"' "production-shared alarms on tss session saturation"
  assert_contains "$monitoring_tf" 'metric_name         = "WithdrawalDLQDepth"' "production-shared wires the withdrawal dlq metric name"
  assert_contains "$monitoring_tf" 'metric_name         = "ConfirmedUnmarkedCount"' "production-shared wires the confirmed-unmarked metric name"
  assert_contains "$monitoring_tf" 'metric_name         = "MarkPaidCircuitOpen"' "production-shared wires the mark-paid circuit metric name"
  assert_contains "$monitoring_tf" 'metric_name         = "DepositProofRequestedCount"' "production-shared wires the deposit proof-requested metric name"
  assert_contains "$monitoring_tf" 'metric_name         = "DepositSubmittedCount"' "production-shared wires the deposit submitted metric name"
  assert_contains "$monitoring_tf" 'metric_name         = "MinWithdrawalTimeToExpirySeconds"' "production-shared wires the withdrawal expiry metric name"
  assert_contains "$monitoring_tf" 'metric_name         = "CheckpointPinBacklog"' "production-shared wires the checkpoint pin backlog metric name"
  assert_contains "$monitoring_tf" 'metric_name         = "TSSSessionSaturation"' "production-shared wires the tss session saturation metric name"
  assert_contains "$monitoring_tf" 'operations_metric_namespace = "IntentsJuno/Operations"' "production-shared defines the custom operations metric namespace"
  assert_contains "$monitoring_tf" 'namespace           = local.operations_metric_namespace' "production-shared uses the custom operations metric namespace"

  assert_not_contains "$password_block" 'default' "shared postgres password has no default"
  assert_contains "$variables_tf" 'variable "shared_proof_service_image_ecr_repository_arn"' "explicit proof-service ECR repository ARN input"
  assert_contains "$shared_ecs_desired_count_block" 'default     = 0' "shared proof services stay idle until runtime rollout"
  assert_contains "$shared_proof_requestor_desired_count_block" 'default     = null' "proof-requestor desired count defaults to the shared proof count"
  assert_contains "$shared_proof_funder_desired_count_block" 'default     = null' "proof-funder desired count defaults to the shared proof count"

  assert_contains "$key_rotation" 'configured proof-services ECR repository' "rotation runbook documents scoped repository access"
  assert_contains "$key_rotation" 'aws autoscaling start-instance-refresh' "rotation runbook documents proof-role instance refresh"
  assert_contains "$failover" 'proof-role autoscaling group' "failover runbook documents proof-role failover ownership"
  assert_contains "$failover" 'at least two healthy targets' "failover runbook documents IPFS redundancy"
  assert_contains "$failover" 'ELB health checks' "failover runbook documents ELB-backed readiness"
  assert_contains "$restore_runbook" 'backup list-recovery-points-by-backup-vault' "aurora dr runbook enumerates recovery points"
  assert_contains "$restore_runbook" 'backup start-restore-job' "aurora dr runbook documents restore execution"

  printf 'package_a_snapshot_test: PASS\n'
}

main "$@"
