#!/usr/bin/env bash
# shellcheck shell=bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
source "$REPO_ROOT/deploy/production/tests/common_test.sh"

assert_not_contains() {
  local haystack="$1"
  local needle="$2"
  local msg="$3"
  if [[ "$haystack" == *"$needle"* ]]; then
    printf 'assert_not_contains failed: %s: found=%q\n' "$msg" "$needle" >&2
    exit 1
  fi
}

main() {
  local main_tf variables_tf monitoring_tf outputs_tf versions_tf password_block key_rotation failover restore_runbook min_healthy_count max_healthy_count rollback_count
  main_tf="$(cat "$SCRIPT_DIR/main.tf")"
  variables_tf="$(cat "$SCRIPT_DIR/variables.tf")"
  monitoring_tf="$(cat "$SCRIPT_DIR/monitoring.tf")"
  outputs_tf="$(cat "$SCRIPT_DIR/outputs.tf")"
  versions_tf="$(cat "$SCRIPT_DIR/versions.tf")"
  password_block="$(awk '
    /variable "shared_postgres_password" \{/ { in_block = 1 }
    in_block { print }
    in_block && /^\}/ { exit }
  ' "$SCRIPT_DIR/variables.tf")"
  shared_ecs_desired_count_block="$(awk '
    /variable "shared_ecs_desired_count" \{/ { in_block = 1 }
    in_block { print }
    in_block && /^\}/ { exit }
  ' "$SCRIPT_DIR/variables.tf")"
  key_rotation="$(cat "$REPO_ROOT/deploy/shared/runbooks/proof-key-rotation.md")"
  failover="$(cat "$REPO_ROOT/deploy/shared/runbooks/proof-requestor-failover.md")"
  restore_runbook="$(cat "$REPO_ROOT/deploy/shared/runbooks/aurora-dr-restore.md")"

  assert_contains "$main_tf" 'check "distinct_proof_secret_arns"' "distinct proof secret ARN guard"
  assert_contains "$versions_tf" 'backend "s3" {}' "production-shared declares an s3 backend block for coordinator bootstrap"
  assert_contains "$main_tf" 'check "proof_service_image_ecr_scope"' "explicit ECR image repository scope guard"
  assert_contains "$main_tf" 'check "shared_ecs_private_subnets_when_no_public_ip"' "shared ecs subnet/public-ip compatibility guard"
  assert_contains "$main_tf" 'shared_proof_service_image_ecr_repository_arn must be set when shared_proof_service_image points at an explicit ECR repository.' "explicit ECR image scope message"
  assert_contains "$main_tf" 'shared proof services require private shared_subnet_ids when shared_ecs_assign_public_ip=false.' "production-shared fails closed on public shared subnets without public IPs"
  assert_contains "$main_tf" 'shared_kafka_cluster_arn                     = coalesce(aws_msk_cluster.shared.arn, "")' "production-shared guards the shared kafka cluster arn when Terraform has not populated it yet"
  assert_contains "$main_tf" 'shared_kafka_topic_arn_prefix                = replace(local.shared_kafka_cluster_arn, ":cluster/", ":topic/")' "production-shared derives kafka topic arns from the guarded cluster arn"
  assert_contains "$main_tf" 'shared_kafka_group_arn_prefix                = replace(local.shared_kafka_cluster_arn, ":cluster/", ":group/")' "production-shared derives kafka group arns from the guarded cluster arn"

  assert_not_contains "$main_tf" 'AmazonECSTaskExecutionRolePolicy' "managed ECS execution policy removed"
  assert_contains "$main_tf" 'sid = "AllowECRAuthorizationToken"' "execution role keeps required ECR auth token call"
  assert_contains "$main_tf" 'sid = "AllowProofRequestorImagePull"' "requestor execution role scopes image pull"
  assert_contains "$main_tf" 'sid = "AllowProofFunderImagePull"' "funder execution role scopes image pull"
  assert_contains "$main_tf" 'resources = [local.shared_proof_service_ecr_repository_arn]' "ECR image pull scope uses configured repository ARN"
  assert_contains "$main_tf" 'sid = "AllowProofRequestorLogWrite"' "requestor log write scope present"
  assert_contains "$main_tf" 'sid = "AllowProofFunderLogWrite"' "funder log write scope present"
  assert_contains "$main_tf" 'trimsuffix(aws_cloudwatch_log_group.proof_requestor.arn, ":*")' "requestor log group scope is explicit"
  assert_contains "$main_tf" 'trimsuffix(aws_cloudwatch_log_group.proof_funder.arn, ":*")' "funder log group scope is explicit"
  assert_contains "$main_tf" 'resources = [var.shared_sp1_requestor_secret_arn]' "requestor secret scope uses only requestor ARN"
  assert_contains "$main_tf" 'resources = [var.shared_sp1_funder_secret_arn]' "funder secret scope uses only funder ARN"
  assert_contains "$main_tf" 'resource "aws_secretsmanager_secret" "shared_postgres_dsn"' "production-shared provisions a dedicated postgres dsn secret"
  assert_contains "$main_tf" 'resources = [aws_secretsmanager_secret.shared_postgres_dsn.arn]' "execution roles can read only the shared postgres dsn secret"
  assert_contains "$main_tf" 'resource "aws_secretsmanager_secret" "shared_ipfs_api_bearer_token"' "production-shared provisions a dedicated IPFS API bearer token secret"
  assert_contains "$main_tf" 'resources = [aws_secretsmanager_secret.shared_ipfs_api_bearer_token.arn]' "production-shared constrains IPFS secret reads to the shared IPFS bearer token secret"
  assert_contains "$main_tf" 'resource "aws_secretsmanager_secret" "shared_kafka_critical_hmac_key"' "production-shared provisions a dedicated Kafka critical-topic HMAC secret"
  assert_contains "$main_tf" 'resource "aws_security_group" "wireguard"' "production-shared provisions a dedicated wireguard security group"
  assert_contains "$main_tf" 'resource "aws_instance" "wireguard_gateway"' "production-shared provisions a dedicated wireguard gateway instance"
  assert_contains "$main_tf" 'resource "aws_eip" "wireguard_gateway"' "production-shared provisions a stable public endpoint for wireguard"
  assert_contains "$main_tf" 'resource "aws_secretsmanager_secret" "shared_wireguard_client_config"' "production-shared provisions a secret for the backoffice wireguard client config"
  assert_contains "$main_tf" 'source_dest_check           = false' "production-shared disables source destination checks on the wireguard gateway"
  assert_contains "$main_tf" 'resource "aws_iam_instance_profile" "wireguard_gateway"' "production-shared provisions a wireguard gateway instance profile"
  assert_contains "$main_tf" 'wg genkey' "production-shared bootstraps wireguard peers on first boot"
  assert_contains "$main_tf" '"ec2:DescribeInstances"' "production-shared grants the wireguard gateway permission to look up its elastic ip association"
  assert_contains "$main_tf" 'instance_id="$(curl -fsS -H "X-aws-ec2-metadata-token: $imds_token" http://169.254.169.254/latest/meta-data/instance-id)"' "production-shared records the wireguard instance id during bootstrap"
  assert_contains "$main_tf" "aws --region \${var.aws_region} ec2 describe-instances --instance-ids \"\$instance_id\"" "production-shared waits for the elastic ip to appear via ec2 instead of relying on early imds public-ipv4"
  assert_contains "$main_tf" 'dnsmasq' "production-shared configures dnsmasq for backoffice hostname resolution"
  assert_contains "$main_tf" 'address=/${var.shared_wireguard_backoffice_hostname}/${var.shared_wireguard_backoffice_private_endpoint}' "production-shared maps the backoffice hostname to the private app endpoint over wireguard"
  assert_contains "$main_tf" 'iptables -A FORWARD -i %i -j ACCEPT' "production-shared allows forwarded traffic from the wireguard tunnel"
  assert_contains "$main_tf" 'iptables -A FORWARD -o %i -j ACCEPT' "production-shared allows forwarded return traffic to the wireguard tunnel"
  assert_contains "$main_tf" 'secretsmanager put-secret-value --secret-id "$wireguard_client_config_secret_arn"' "production-shared uploads the generated wireguard client config into Secrets Manager"
  local wg_restart_line
  local dnsmasq_restart_line
  wg_restart_line="$(printf '%s\n' "$main_tf" | grep -n 'systemctl restart wg-quick@wg0' | cut -d: -f1)"
  dnsmasq_restart_line="$(printf '%s\n' "$main_tf" | grep -n 'systemctl restart dnsmasq' | cut -d: -f1)"
  if (( dnsmasq_restart_line <= wg_restart_line )); then
    printf 'wireguard ordering assertion failed: production-shared must start wg0 before dnsmasq (wg=%s dns=%s)\n' "$wg_restart_line" "$dnsmasq_restart_line" >&2
    exit 1
  fi
  assert_contains "$variables_tf" 'variable "shared_sp1_requestor_address"' "production-shared exposes shared proof requestor address input"
  assert_contains "$variables_tf" 'variable "shared_ipfs_data_volume_size_gb"' "production-shared exposes dedicated IPFS data volume sizing"
  assert_contains "$variables_tf" 'variable "shared_wireguard_public_subnet_id"' "production-shared exposes the dedicated wireguard public subnet input"
  assert_contains "$variables_tf" 'variable "shared_wireguard_backoffice_private_endpoint"' "production-shared exposes the private backoffice endpoint input"
  assert_contains "$variables_tf" 'variable "shared_wireguard_backoffice_hostname"' "production-shared exposes the vpn backoffice hostname input"
  assert_contains "$variables_tf" 'alarm_actions must include at least one CloudWatch action ARN.' "production-shared requires alarm actions"
  assert_contains "$outputs_tf" 'output "shared_sp1_requestor_address"' "production-shared exports shared proof requestor address"
  assert_contains "$outputs_tf" 'output "shared_sp1_rpc_url"' "production-shared exports shared sp1 rpc url"
  assert_contains "$outputs_tf" 'output "shared_ipfs_api_auth_secret_arn"' "production-shared exports the shared IPFS bearer token secret ARN"
  assert_contains "$outputs_tf" 'output "shared_kafka_critical_hmac_secret_arn"' "production-shared exports the Kafka critical-topic HMAC secret ARN"
  assert_contains "$outputs_tf" 'output "shared_wireguard_gateway_private_ip"' "production-shared exports the wireguard gateway private ip"
  assert_contains "$outputs_tf" 'output "shared_wireguard_endpoint_host"' "production-shared exports the wireguard public endpoint host"
  assert_contains "$outputs_tf" 'output "shared_wireguard_client_config_secret_arn"' "production-shared exports the wireguard client config secret arn"
  assert_contains "$variables_tf" 'At least two private subnet IDs in distinct AZs for Aurora, MSK, ECS, and the IPFS NLB.' "production-shared documents private shared subnet requirement"
  assert_contains "$variables_tf" $'variable "shared_msk_broker_instance_type" {\n  description = "MSK broker instance type."\n  type        = string\n  default     = "kafka.m5.large"' "production-shared defaults MSK to an IAM-ready broker class"
  assert_contains "$variables_tf" 'variable "shared_base_chain_id"' "production-shared exposes base chain id input"
  assert_contains "$variables_tf" 'variable "shared_deposit_image_id"' "production-shared exposes deposit image id input"
  assert_contains "$variables_tf" 'variable "shared_withdraw_image_id"' "production-shared exposes withdraw image id input"
  assert_contains "$main_tf" 'local.shared_proof_requestor_command' "production-shared requestor task uses generated command"
  assert_contains "$main_tf" '"--sp1-requestor-address", local.shared_sp1_requestor_address' "production-shared requestor command includes requestor address"
  assert_contains "$main_tf" '"--chain-id", tostring(var.shared_base_chain_id)' "production-shared requestor command includes chain id"
  assert_contains "$main_tf" '"--postgres-dsn-env", "POSTGRES_DSN"' "production-shared requestor command resolves DSN from secret-backed env"
  assert_not_contains "$main_tf" '"--postgres-dsn", local.shared_postgres_dsn' "production-shared does not expose Postgres DSN in ECS command lines"
  assert_contains "$main_tf" '"--queue-brokers", local.shared_kafka_bootstrap_brokers' "production-shared proof tasks use IAM kafka brokers"
  assert_contains "$main_tf" 'local.shared_proof_funder_command' "production-shared funder task uses generated command"
  assert_contains "$main_tf" 'name      = "POSTGRES_DSN"' "production-shared injects Postgres DSN as an ECS secret"
  assert_contains "$main_tf" 'valueFrom = aws_secretsmanager_secret.shared_postgres_dsn.arn' "production-shared ECS DSN secret comes from dedicated secret ARN"
  assert_contains "$main_tf" '"--min-balance-wei", tostring(local.shared_sp1_required_credit_buffer)' "production-shared funder command includes min balance"
  assert_contains "$main_tf" '"--critical-balance-wei", tostring(local.shared_sp1_projected_with_overhead)' "production-shared funder command includes critical balance"
  assert_contains "$main_tf" 'name  = "JUNO_QUEUE_KAFKA_AUTH_MODE"' "production-shared proof task env includes kafka auth mode"
  assert_contains "$main_tf" 'value = "aws-msk-iam"' "production-shared proof task env enforces aws-msk-iam"
  assert_contains "$main_tf" 'name  = "JUNO_QUEUE_KAFKA_AWS_REGION"' "production-shared proof task env includes kafka aws region"
  assert_contains "$main_tf" 'value = var.aws_region' "production-shared proof task env propagates aws region"
  assert_contains "$main_tf" 'connectivity_info {' "production-shared configures explicit MSK broker connectivity"
  assert_contains "$main_tf" 'vpc_connectivity {' "production-shared enables explicit VPC connectivity settings for MSK"
  assert_contains "$main_tf" 'client_authentication {' "production-shared renders VPC connectivity auth settings"
  assert_contains "$main_tf" 'sasl {' "production-shared renders VPC connectivity SASL settings"
  assert_contains "$main_tf" 'iam = true' "production-shared enables IAM auth on VPC-connected brokers"
  assert_contains "$main_tf" 'name  = "SP1_NETWORK_RPC_URL"' "production-shared proof task env includes SP1 rpc url"
  assert_contains "$main_tf" 'name  = "SP1_DEPOSIT_PROGRAM_URL"' "production-shared proof task env includes deposit program url"
  assert_contains "$main_tf" 'name  = "SP1_WITHDRAW_PROGRAM_URL"' "production-shared proof task env includes withdraw program url"
  assert_contains "$main_tf" 'shared_sp1_requestor_address must be set when shared_ecs_desired_count > 0' "production-shared blocks active proof services without requestor address"
  assert_contains "$main_tf" 'task_role_arn            = aws_iam_role.proof_requestor_task.arn' "requestor task definition uses dedicated runtime role"
  assert_contains "$main_tf" 'task_role_arn            = aws_iam_role.proof_funder_task.arn' "funder task definition uses dedicated runtime role"
  assert_contains "$main_tf" 'sid = "AllowMSKConnect"' "proof runtime task roles can connect to MSK"
  assert_contains "$main_tf" 'sid = "AllowMSKTopicAccess"' "requestor task role grants broad kafka topic access"
  assert_contains "$main_tf" 'sid = "AllowMSKGroupAccess"' "requestor task role grants broad kafka group access"
  assert_contains "$main_tf" '"kafka-cluster:DescribeTopicDynamicConfiguration"' "requestor task role can inspect kafka topic configuration"
  assert_contains "$main_tf" '"kafka-cluster:WriteDataIdempotently"' "requestor task role supports idempotent kafka writes"
  assert_contains "$main_tf" 'resources = ["${local.shared_kafka_topic_arn_prefix}/*"]' "requestor task role scopes topic access to the shared cluster"
  assert_contains "$main_tf" 'resources = ["${local.shared_kafka_group_arn_prefix}/*"]' "requestor task role scopes group access to the shared cluster"
  assert_contains "$main_tf" 'sid = "AllowReadProofRequestsTopic"' "requestor task role can read proof request topic"
  assert_contains "$main_tf" 'sid = "AllowWriteProofResultsTopic"' "requestor task role can write fulfillment topic"
  assert_contains "$main_tf" 'sid = "AllowWriteProofFailuresTopic"' "requestor task role can write failure topic"
  assert_contains "$main_tf" 'sid = "AllowReadProofRequestorGroup"' "requestor task role can use its consumer group"
  assert_contains "$main_tf" 'sid = "AllowWriteOpsAlertsTopic"' "funder task role can emit ops alerts"

  assert_contains "$main_tf" 'description = "MSK broker mesh"' "MSK self-ingress rule exists"
  assert_contains "$main_tf" 'protocol    = "tcp"' "MSK self-ingress stays on TCP"
  assert_contains "$main_tf" 'from_port   = 9092' "MSK self-ingress lower port bound"
  assert_contains "$main_tf" 'to_port     = 9094' "MSK self-ingress upper port bound"
  assert_contains "$main_tf" 'min.insync.replicas = 2' "MSK durability policy"

  assert_contains "$main_tf" 'skip_final_snapshot       = false' "Aurora final snapshot required"
  assert_contains "$main_tf" 'final_snapshot_identifier = local.aurora_final_snapshot_identifier' "Aurora final snapshot identifier wired"
  assert_contains "$main_tf" 'deletion_protection       = true' "Aurora deletion protection enabled"

  min_healthy_count="$(grep -c 'deployment_minimum_healthy_percent = 100' "$SCRIPT_DIR/main.tf")"
  max_healthy_count="$(grep -c 'deployment_maximum_percent         = 200' "$SCRIPT_DIR/main.tf")"
  rollback_count="$(grep -c 'rollback = true' "$SCRIPT_DIR/main.tf")"
  assert_eq "$min_healthy_count" "2" "both proof services keep minimum healthy percent at 100"
  assert_eq "$max_healthy_count" "2" "both proof services keep maximum percent at 200"
  assert_eq "$rollback_count" "2" "both proof services keep rollback enabled"

  assert_contains "$main_tf" 'health_check_type         = "ELB"' "IPFS ASG uses ELB health"
  assert_contains "$main_tf" 'shared_ipfs_min_size must be at least 2 to avoid a single-node IPFS deployment.' "IPFS redundancy precondition"
  assert_contains "$main_tf" 'volume_size           = var.shared_ipfs_data_volume_size_gb' "production-shared provisions a dedicated IPFS data volume"
  assert_contains "$main_tf" 'delete_on_termination = false' "production-shared preserves the dedicated IPFS data volume across instance replacement"
  assert_contains "$main_tf" '/var/lib/intents-juno/ipfs' "production-shared mounts a dedicated IPFS data path"
  assert_contains "$main_tf" 'enable_cross_zone_load_balancing = true' "production-shared enables cross-zone load balancing on the IPFS NLB"
  assert_not_contains "$main_tf" 'apt-get install -y awscli' "production-shared no longer depends on the missing Ubuntu awscli package for IPFS bootstrap"
  assert_contains "$main_tf" 'arch="$(uname -m)"' "production-shared detects the IPFS instance architecture before installing AWS CLI"
  assert_contains "$main_tf" 'awscli-exe-linux-$${awscli_arch}.zip' "production-shared installs AWS CLI from the official architecture-specific bundle"
  assert_contains "$main_tf" '/tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update' "production-shared installs AWS CLI v2 into a stable location"
  assert_contains "$main_tf" 'secretsmanager get-secret-value --secret-id "$ipfs_api_secret_arn"' "production-shared bootstraps the IPFS bearer token from Secrets Manager"
  assert_contains "$main_tf" 'proxy_pass http://127.0.0.1:5001;' "production-shared proxies authenticated IPFS API traffic to loopback Kubo"
  assert_contains "$main_tf" 'daemon --migrate=true --api /ip4/127.0.0.1/tcp/5001 --routing=dhtclient' "production-shared binds raw Kubo API to loopback only"
  assert_not_contains "$main_tf" '--api /ip4/0.0.0.0/tcp/5001' "production-shared no longer exposes raw Kubo on all interfaces"
  assert_contains "$main_tf" 'data "aws_route_table" "shared"' "production-shared resolves route tables for shared subnets"
  assert_contains "$main_tf" 'resource "aws_security_group" "shared_vpc_endpoints"' "production-shared provisions a dedicated security group for interface endpoints"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "secretsmanager"' "production-shared provisions a Secrets Manager VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "ecr_api"' "production-shared provisions an ECR API VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "ecr_dkr"' "production-shared provisions an ECR DKR VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "sts"' "production-shared provisions an STS VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "kms"' "production-shared provisions a KMS VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "logs"' "production-shared provisions a CloudWatch Logs VPC endpoint"
  assert_contains "$main_tf" 'resource "aws_vpc_endpoint" "s3"' "production-shared provisions an S3 gateway endpoint"
  assert_contains "$main_tf" 'description = "HTTPS from the VPC"' "production-shared opens interface endpoints to the whole VPC"
  assert_contains "$main_tf" 'cidr_blocks = [data.aws_vpc.selected.cidr_block]' "production-shared interface endpoints allow non-shared subnets"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.secretsmanager"' "production-shared points the Secrets Manager endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.ecr.api"' "production-shared points the ECR API endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.ecr.dkr"' "production-shared points the ECR DKR endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.sts"' "production-shared points the STS endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.kms"' "production-shared points the KMS endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name        = "com.amazonaws.${var.aws_region}.logs"' "production-shared points the CloudWatch Logs endpoint at the deployment region"
  assert_contains "$main_tf" 'service_name      = "com.amazonaws.${var.aws_region}.s3"' "production-shared points the S3 endpoint at the deployment region"
  assert_contains "$main_tf" 'route_table_ids   = local.shared_route_table_ids' "production-shared attaches the S3 gateway endpoint to the shared route tables"
  assert_contains "$main_tf" 'security_group_ids  = [aws_security_group.shared_vpc_endpoints.id]' "production-shared constrains interface endpoints behind the dedicated SG"
  assert_contains "$main_tf" 'private_dns_enabled = true' "production-shared enables private DNS on interface endpoints"
  assert_contains "$main_tf" 'alias  = "dr"' "production-shared configures an aws dr provider alias"
  assert_contains "$variables_tf" 'variable "shared_postgres_dr_region"' "production-shared exposes the Aurora DR backup region"
  assert_not_contains "$variables_tf" 'trimspace(var.shared_postgres_dr_region) != trimspace(var.aws_region)' "production-shared no longer uses cross-variable validation in shared_postgres_dr_region"
  assert_contains "$main_tf" 'resource "aws_backup_vault" "shared_postgres"' "production-shared provisions a primary backup vault"
  assert_contains "$main_tf" 'resource "aws_backup_vault" "shared_postgres_dr"' "production-shared provisions a DR backup vault"
  assert_contains "$main_tf" 'provider = aws.dr' "production-shared binds DR backup resources to the dr provider"
  assert_contains "$main_tf" 'resource "aws_backup_plan" "shared_postgres"' "production-shared provisions an Aurora backup plan"
  assert_contains "$main_tf" 'copy_action {' "production-shared copies backups into the DR vault"
  assert_contains "$main_tf" 'destination_vault_arn = aws_backup_vault.shared_postgres_dr.arn' "production-shared targets the DR backup vault"
  assert_contains "$main_tf" 'resource "aws_backup_selection" "shared_postgres"' "production-shared selects the Aurora cluster for AWS Backup"
  assert_contains "$main_tf" 'resources    = [aws_rds_cluster.shared.arn]' "production-shared backs up the Aurora cluster ARN"
  assert_contains "$main_tf" 'resource "aws_iam_role" "shared_backup"' "production-shared provisions a dedicated AWS Backup role"
  assert_contains "$main_tf" 'AWSBackupServiceRolePolicyForBackup' "production-shared attaches the AWS Backup backup policy"
  assert_contains "$main_tf" 'AWSBackupServiceRolePolicyForRestores' "production-shared attaches the AWS Backup restore policy"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "withdrawal_dlq_depth"' "production-shared alarms on withdrawal dlq depth"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "confirmed_unmarked_count"' "production-shared alarms on confirmed-unmarked withdrawals"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "min_withdrawal_time_to_expiry_seconds"' "production-shared alarms on withdrawal expiry runway"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "checkpoint_pin_backlog"' "production-shared alarms on checkpoint pin backlog"
  assert_contains "$monitoring_tf" 'resource "aws_cloudwatch_metric_alarm" "tss_session_saturation"' "production-shared alarms on tss session saturation"
  assert_contains "$monitoring_tf" 'metric_name         = "WithdrawalDLQDepth"' "production-shared wires the withdrawal dlq metric name"
  assert_contains "$monitoring_tf" 'metric_name         = "ConfirmedUnmarkedCount"' "production-shared wires the confirmed-unmarked metric name"
  assert_contains "$monitoring_tf" 'metric_name         = "MinWithdrawalTimeToExpirySeconds"' "production-shared wires the withdrawal expiry metric name"
  assert_contains "$monitoring_tf" 'metric_name         = "CheckpointPinBacklog"' "production-shared wires the checkpoint pin backlog metric name"
  assert_contains "$monitoring_tf" 'metric_name         = "TSSSessionSaturation"' "production-shared wires the tss session saturation metric name"
  assert_contains "$monitoring_tf" 'operations_metric_namespace = "IntentsJuno/Operations"' "production-shared defines the custom operations metric namespace"
  assert_contains "$monitoring_tf" 'namespace           = local.operations_metric_namespace' "production-shared uses the custom operations metric namespace"

  assert_not_contains "$password_block" 'default' "shared postgres password has no default"
  assert_contains "$variables_tf" 'variable "shared_proof_service_image_ecr_repository_arn"' "explicit proof-service ECR repository ARN input"
  assert_contains "$shared_ecs_desired_count_block" 'default     = 0' "shared proof services stay idle until runtime rollout"

  assert_contains "$key_rotation" 'configured proof-services ECR repository' "rotation runbook documents scoped repository access"
  assert_contains "$key_rotation" 'deployment_maximum_percent = 200' "rotation runbook documents overlapping rollout"
  assert_contains "$failover" 'at least two healthy targets' "failover runbook documents IPFS redundancy"
  assert_contains "$failover" 'ELB health checks' "failover runbook documents ELB-backed readiness"
  assert_contains "$restore_runbook" 'backup list-recovery-points-by-backup-vault' "aurora dr runbook enumerates recovery points"
  assert_contains "$restore_runbook" 'backup start-restore-job' "aurora dr runbook documents restore execution"

  printf 'package_a_snapshot_test: PASS\n'
}

main "$@"
